Repository konflux-ci/e2e-tests, pull requests merged in 2022-11, with the labels that each got.

#225 fix: do not change pipeline bundle name
  tests/build/build.go
Labels: lgtm, approved

#147 feat: Add cron triggered pipeline for IC rotation.
  pipelines/interrupt_catcher/clusterrole.yaml
  pipelines/interrupt_catcher/clusterrolebinding.yaml
  pipelines/interrupt_catcher/eventlistener.yaml
  pipelines/interrupt_catcher/rolebinding.yaml
  pipelines/interrupt_catcher/serviceaccount.yaml
  pipelines/interrupt_catcher/triggerbinding.yaml
  pipelines/interrupt_catcher/triggertemplate.yaml
Labels: lgtm, approved

#231 fix: RHPD-557 use volumeClaim Template instead of persistentVolumeClaim
  .tekton/pull-request.yaml
  .tekton/push.yaml
Labels: lgtm, approved

#221 feat: add task sbom-json-check to e2e test
  pkg/utils/build/hacbs.go
  pkg/utils/has/controller.go
  tests/build/build.go
Labels: lgtm, approved

#236 feat: HACBS-973 add ClamAV results to HACBS pipeline
  tests/build/build.go
Labels: lgtm, approved

#232 feat: Add happy path test cases for integration service
  pkg/utils/integration/controller.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#237 fix: integration svc: wait for PipelineRun init
  tests/integration-service/integration.go
Labels: lgtm, approved

#233 chore: add mage target to cleanup old workspaces on cps
  LICENSE
  README.md
  go.mod
  go.sum
  magefiles/magefile.go
  magefiles/utils.go
  pkg/apis/kubernetes/client.go
  pkg/utils/kcp/controller.go
  pkg/utils/util.go
Labels: lgtm, approved

#235 refactor: add controllers for workspaces & ocp
  README.md
  cmd/loadTests.go
  go.mod
  go.sum
  magefiles/magefile.go
  magefiles/utils.go
  pkg/apis/kubernetes/client.go
  pkg/framework/framework.go
  pkg/utils/build/hacbs.go
  pkg/utils/common/controller.go
  pkg/utils/gitops/controller.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  pkg/utils/jvmbuildservice/controller.go
  pkg/utils/kcp/controller.go
  pkg/utils/release/controller.go
  pkg/utils/spi/controller.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/matchers.go
  pkg/utils/tekton/matchers_test.go
  scripts/install-appstudio-kcp.sh
  tests/build/build.go
  tests/build/chains.go
  tests/build/jvm-build.go
  tests/cluster-registration/clusters.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
Labels: approved

#238 fix: remove references to "pre-kcp" branch
  .github/workflows/build.yaml
  scripts/e2e-openshift-ci.sh
  scripts/install-appstudio-e2e-mode.sh
  scripts/install-appstudio.sh
Labels: lgtm, approved

#243 fix: infra-deployments PR job
  magefiles/magefile.go
Labels: lgtm, approved

#245 fix: ignore ci bots accounts as authors
  magefiles/magefile.go
Labels: lgtm, approved

#246 chore: Update appstudio(stonesoup) apis to latest version
  Dockerfile
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
  scripts/e2e-openshift-ci.sh
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#249 fix: infra-deployments PR pairing
  magefiles/magefile.go
  magefiles/types.go
  magefiles/utils.go
Labels: lgtm, approved

#247 chore: update tektoncd/pipeline module (v0.37.0)
  go.mod
  go.sum
  pkg/utils/build/hacbs.go
  pkg/utils/has/controller.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/matchers.go
  pkg/utils/tekton/matchers_test.go
Labels: lgtm, approved

#248 fix: Remove .ci folder and update go.mod to 1.18
  .ci/oci-launch-e2e.sh
  .ci/openshift-ci/Dockerfile
  .github/workflows/PR.yaml
  README.md
  go.mod
Labels: lgtm, approved

#250 chore: Allow more flexible control vault podname and namespace
  scripts/spi-e2e-setup.sh
Labels: lgtm, approved

#241 chore: RHDP 540 Polarion test cases reporter backport to the new main
  README.md
  cmd/e2e_test.go
  go.mod
  go.sum
  magefiles/magefile.go
  pkg/framework/polarion_reporter.go
Labels: lgtm, approved

#254 test: PLNSRVCE-693: work with repo url which ends with .git
  tests/build/build.go
Labels: lgtm, approved

#252 test: Fix release e2e test happy path
  go.mod
  go.sum
  pkg/utils/release/controller.go
  pkg/utils/tekton/controller.go
  tests/build/chains.go
  tests/release/const.go
  tests/release/release.go
Labels: lgtm, ok-to-test, approved

#255 fix: fix multi-component detection test
  go.sum
  tests/e2e-demos/multi-component.go
Labels: lgtm, approved
