Repository konflux-ci/e2e-tests, pull requests merged in 2022-07, with the labels that each got.

#134 test: Add integration service test suite to e2e-tests
  cmd/e2e_test.go
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/framework/describe.go
  pkg/framework/framework.go
  pkg/utils/integration/controller.go
  tests/integration-service/integration.go
Labels: lgtm

#135 test: [Hacbs 650]/failure missing release strategy
  tests/release/release-failures.go
  tests/release/release.go
Labels: lgtm, ok-to-test, approved

#141 feat: Add nodejs very simple application for tests
  tests/e2e-demos/config/default.yaml
  tests/integration-service/integration.go
Labels: lgtm, approved

#140 test: Hacbs 834/create constants module in release tests folder
  tests/release/const.go
  tests/release/release-failures.go
  tests/release/release.go
Labels: lgtm, needs-ok-to-test, approved

#109 test: build multiple components from input
  .github/workflows/PR.yaml
  pkg/framework/describe.go
  pkg/utils/common/controller.go
  tests/build/README.md
  tests/build/build.go
  tests/build/const.go
Labels: lgtm, approved

#103 refactor: add debug info for chain e2e test
  pkg/utils/tekton/controller.go
  tests/build/chains.go
Labels: lgtm, approved

#148 fix: skip chains tests
  tests/build/chains.go
Labels: lgtm, approved

#142 feat: PLNSRVCE-452: add initial e2e test for jvm-build-service
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/framework/describe.go
  pkg/framework/framework.go
  pkg/utils/jvmbuildservice/controller.go
  pkg/utils/tekton/controller.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#150 fix: jvm-build-test
  tests/build/jvm-build.go
Labels: lgtm, approved

#153 fix: vault plus build e2e
  scripts/install-appstudio-e2e-mode.sh
  scripts/spi-e2e-setup.sh
  tests/build/build.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#151 fix: everything in Enterprise contract tests suite
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/framework/describe.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/controller_test.go
  pkg/utils/tekton/matchers.go
  pkg/utils/tekton/pipelines.go
  tests/build/chains.go
Labels: lgtm, approved

#128 test: add component replica scale test
  pkg/utils/has/controller.go
  tests/e2e-demos/Readme.md
  tests/e2e-demos/config/default.yaml
  tests/e2e-demos/config/types.go
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved

#156 ci: preview mode is now setting SPI and waiting for deployment
  .ci/oci-launch-e2e.sh
  scripts/install-appstudio-e2e-mode.sh
Labels: lgtm, approved
