Repository konflux-ci/e2e-tests, pull requests merged in 2022-08, with the labels that each got.

#108 feat: RHDP-453 Add Test labels
  .github/pull_request_template.md
  README.md
  docs/LabelsNaming.md
  pkg/framework/describe.go
  scripts/install-appstudio-e2e-mode.sh
  tests/build/build.go
  tests/build/chains.go
  tests/build/jvm-build.go
  tests/cluster-registration/clusters.go
  tests/e2e-demos/e2e-demo.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
  tests/release/release-failures.go
  tests/release/release.go
Labels: lgtm, approved

#160 fix: skip `ec` tests for now
  .ci/oci-launch-e2e.sh
Labels: lgtm, approved

#161 fix: Wait for Argo CD Role/RoleBindings on Namespace creation, and cleanup PipelineRuns on Namespace deletion
  pkg/apis/kubernetes/client.go
  pkg/utils/common/controller.go
  pkg/utils/has/controller.go
  pkg/utils/tekton/controller.go
  tests/build/build.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#163 fix: build: image repo protection test
  tests/build/build.go
Labels: lgtm, approved

#155 feat: PLNSRVCE-538: add jvm build service test back (but with less expensive repo resource wise)
  pkg/utils/tekton/controller.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#165 fix: disable jvm-build-service tests temporarily
  tests/build/jvm-build.go
Labels: lgtm, approved

#168 fix: Fix the jvm build service tests
  tests/build/jvm-build.go
Labels: lgtm, approved

#158 feat: e2e tests for verify-enterprise-contract-v2
  .ci/oci-launch-e2e.sh
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/controller_test.go
  pkg/utils/tekton/matchers.go
  pkg/utils/tekton/matchers_test.go
  pkg/utils/tekton/pipelines.go
  tests/build/chains.go
Labels: lgtm, approved

#169 fix: comment out jvm tests yet again
  pkg/utils/tekton/controller.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#162 feat: Add field validation to the SBOM test
  pkg/utils/build/sbom.go
  tests/build/build.go
Labels: lgtm, approved

#173 fix: improve method for removing PR finalizers
  pkg/utils/tekton/controller.go
Labels: lgtm, approved

#164 docs: RHDP-528 E2E tests documentation update
  README.md
  docs/DeveloperFocus.md
  docs/Installation.md
  docs/LoadTests.md
  docs/OpenShiftCI.md
  docs/Tokens.md
  tests/README.md
  tests/build/README.md
  tests/e2e-demos/README.md
  tests/has/README.md
Labels: lgtm, approved

#172 feat: Remove verify-enterprise-contract (v1) task
  tests/build/chains.go
Labels: lgtm, approved

#174 feat: Run chains tests on dedicated namespace
  pkg/constants/constants.go
  tests/build/chains.go
Labels: lgtm, approved

#176 feat: Add in jvm-build-service tests again
  cmd/loadTests.go
  pkg/utils/has/controller.go
  tests/build/build.go
  tests/build/jvm-build.go
  tests/e2e-demos/e2e-demo.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#175 feat: Component deletion tests
  tests/has/devfile_source.go
Labels: lgtm, approved

#178 fix: improve error message for missing pipeline sa
  pkg/utils/common/controller.go
Labels: lgtm, approved

#171 fix: change the arguments as a list
  pkg/framework/describe.go
Labels: lgtm, approved

#181 fix: jvm-build: improve logging, failure handling
  cmd/e2e_test.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#182 fix: removed release tests to fix CI
  tests/release/const.go
  tests/release/release-failures.go
  tests/release/release.go
Labels: lgtm, ok-to-test, approved

#139 chore: QUAY private image deploy in appstudio
  .ci/oci-launch-e2e.sh
  .gitignore
  README.md
  cmd/e2e_test.go
  go.mod
  pkg/constants/constants.go
  pkg/utils/gitops/controller.go
  pkg/utils/spi/controller.go
  pkg/utils/util.go
  scripts/install-appstudio-e2e-mode.sh
  scripts/spi-e2e-setup.sh
  tests/build/chains.go
  tests/e2e-demos/README.md
  tests/e2e-demos/config/config.go
  tests/e2e-demos/config/default.yaml
  tests/e2e-demos/const.go
  tests/e2e-demos/e2e-demo.go
  tests/has/const.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: approved

#149 chore: Run e2e tests in parallel
  magefiles/magefile.go
  pkg/utils/util.go
  tests/build/build.go
  tests/build/jvm-build.go
  tests/e2e-demos/e2e-demo.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
Labels: approved
