Repository konflux-ci/e2e-tests, pull requests merged in 2022-06, with the labels that each got.

#95 fix: Update expected empty data error
  tests/build/chains.go
Labels: lgtm

#86 feat: use pipeline image from config map
  pkg/utils/common/controller.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/controller_test.go
  pkg/utils/tekton/matchers.go
  pkg/utils/tekton/matchers_test.go
  pkg/utils/tekton/pipelines.go
  pkg/utils/tekton/tasks.go
  tests/build/chains.go
Labels: lgtm

#100 fix: Skip enterprise contract tests temporarily
  tests/build/chains.go
Labels: lgtm

#107 test: [DEVHAS-74] Add ComponentDetectionQuery to HAS e2e tests
  pkg/utils/has/controller.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: lgtm

#105 test: additional build-service tests
  go.mod
  go.sum
  pkg/apis/github/api.go
  pkg/apis/github/client.go
  pkg/apis/github/repositories.go
  pkg/apis/github/webhook.go
  pkg/constants/constants.go
  pkg/utils/common/controller.go
  pkg/utils/has/controller.go
  pkg/utils/util.go
  scripts/install-appstudio-e2e-mode.sh
  tests/build/build.go
  tests/e2e-demos/quarkus_curated.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: lgtm

#106 feat: Add release test-suite, demo M5 happy path
  cmd/e2e_test.go
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/framework/describe.go
  pkg/framework/framework.go
  pkg/utils/release/controller.go
  tests/release/release.go
Labels: lgtm

#110 chore: Add launch.json with debug configuration.
  .vscode/launch.json
  README.md
Labels: lgtm

#113 fix: Remove yq installation from dockerfile
  .ci/openshift-ci/Dockerfile
Labels: lgtm

#115 fix: Hacbs 701/move namespace funcs
  pkg/utils/common/controller.go
  pkg/utils/has/controller.go
  pkg/utils/release/controller.go
  tests/build/build.go
  tests/e2e-demos/quarkus_curated.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/release/release.go
Labels: lgtm

#119 fix: Linter go version issues
  .github/workflows/PR.yaml
Labels: lgtm

#118 chore: Add OWNERS file
  OWNERS
Labels: lgtm, approved

#98 feat: Create a test generator to generate different tests scenarios for appstudio e2e demos
  cmd/e2e_test.go
  go.mod
  go.sum
  pkg/framework/describe.go
  pkg/utils/gitops/controller.go
  pkg/utils/has/controller.go
  tests/e2e-demos/Readme.md
  tests/e2e-demos/config/default.yaml
  tests/e2e-demos/config/types.go
  tests/e2e-demos/const.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/quarkus_curated.go
  tests/has/devfile_source.go
  tests/release/release.go
Labels: lgtm, approved

#121 fix: test-container
  Dockerfile
Labels: lgtm, approved

#111 test: build: verify sbom files present in image
  go.mod
  go.sum
  pkg/utils/build/sbom.go
  tests/build/build.go
Labels: lgtm, approved

#120 feat: Hacbs 679/e2e tests applicationsnapshot GitOps api
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/utils/release/controller.go
  tests/release/release.go
Labels: approved

#101 fix: Unskip and fix failing EC tests
  tests/build/chains.go
Labels: lgtm, approved

#97 chore: Add Load testing Scripts
  .gitignore
  README.md
  cmd/loadTests.go
  docs/LoadTests.md
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/constants/constants.go
  pkg/utils/common/controller.go
  pkg/utils/util.go
  tests/load-tests/clear.sh
  tests/load-tests/loadtest.go
  tests/load-tests/run.sh
Labels: lgtm, approved

#112 test: add has application delete test
  pkg/utils/has/controller.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: lgtm, approved

#129 feat: RHDP-442 Update webhook parameters
  pkg/framework/webhook.go
  webhookConfig.yml
Labels: lgtm, approved

#124 test: [Hacbs 648]/failure1
  go.mod
  go.sum
  pkg/utils/common/controller.go
  pkg/utils/release/controller.go
  tests/release/release-failures.go
  tests/release/release.go
Labels: lgtm, ok-to-test, approved

#136 fix: release: runtime error
  pkg/utils/common/controller.go
  tests/release/release-failures.go
Labels: lgtm, approved
