Repository konflux-ci/e2e-tests, pull requests merged in 2022-05, with the labels that each got.

#60 fix: Cleanup buildah-demo task
  pkg/utils/tekton/tasks.go
Labels: lgtm, ok-to-test

#62 fix: Remove unused checks
  tests/has/devfile_source.go
Labels: lgtm

#61 feat: Add coverage for verify-ec task
  go.mod
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/tasks.go
  tests/build/chains.go
Labels: lgtm, ok-to-test

#66 test: Use Go 1.17 to build e2e-tests
  .ci/openshift-ci/Dockerfile
  Dockerfile
Labels: lgtm

#67 fix: build-service test: increase timeout
  tests/build/build.go
Labels: lgtm

#70 fix: unify output image name for all test suites
  tests/build/build.go
  tests/has/Readme.md
  tests/has/devfile_source.go
Labels: lgtm

#72 ci: setup Pipelines-as-Code for e2e-tests
  .tekton/pull-request.yaml
  .tekton/push.yaml
Labels: lgtm

#74 ci: Add script to setup SPI for e2e tests
  .ci/oci-launch-e2e.sh
  scripts/spi-e2e-setup.sh
Labels: lgtm

#71 docs: Developer focused e2e update
  docs/DeveloperFocus.md
  docs/Installation.md
Labels: lgtm, needs-ok-to-test

#81 docs: Add a Pull Request template to the redhat-appstudio/e2e-tests
  .github/pull_request_template.md
Labels: lgtm

#83 fix: Disable openshift ci user provision in external repos
  scripts/e2e-openshift-ci.sh
Labels: lgtm

#79 test: build: test pipeline bundle reference
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/utils/common/controller.go
  tests/build/build.go
Labels: lgtm

#90 fix: adjust to the latest ec-policy output
  tests/build/chains.go
  tests/e2e-demos/const.go
Labels: lgtm

#63 test: Add e2e tests for private git repos
  .ci/openshift-ci/Dockerfile
  docs/Installation.md
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/constants/constants.go
  pkg/framework/framework.go
  pkg/utils/spi/controller.go
  tests/has/Readme.md
  tests/has/const.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: lgtm

#91 fix: Add command to initialize SPI vault
  scripts/install-appstudio-e2e-mode.sh
Labels: lgtm

#92 fix: remove duplicate SPI setup
  .ci/oci-launch-e2e.sh
  scripts/spi-e2e-setup.sh
Labels: lgtm
