Repository konflux-ci/e2e-tests, pull requests merged in 2023-01, with the labels that each got.

#283 fix: sbom - delete extracted image
  pkg/utils/build/sbom.go
Labels: lgtm, approved

#280 feat: speed-up pipelines by skipping checks for initial runs
  pkg/utils/has/controller.go
  pkg/utils/tekton/pipelines.go
  tests/build/build.go
Labels: lgtm, approved

#286 fix: language in devfile changed from java to Java
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: lgtm, approved

#285 fix: remove deprecated ginkgo flag (--progress)
  magefiles/magefile.go
Labels: lgtm, approved

#282 feat: Generate user's kubeconfig
  magefiles/magefile.go
  magefiles/utils.go
  pkg/utils/util.go
  scripts/install-appstudio.sh
Labels: lgtm, approved

#281 fix: revert - disable release tests
  tests/release/release.go
Labels: lgtm, approved

#268 feat(HACBS-1403): improve the e2e test scenario for integration-service
  pkg/utils/integration/controller.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#289 fix: update the chains and release tests to use the ec-defaults configMap
  tests/build/chains.go
  tests/release/release.go
Labels: lgtm, approved

#291 test(RHDP-579): remove 'Ordered' in [e2e-demos-suite]
  pkg/framework/describe.go
  tests/e2e-demos/multi-component.go
Labels: lgtm, ok-to-test, approved

#288 fix(RHDP-563): use the new Stonesoup/AppStudio Environment API to generate GitOpsDeployment
  pkg/framework/custom_junit_reporter.go
  pkg/utils/gitops/controller.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
  pkg/utils/spi/controller.go
  pkg/utils/util.go
  tests/build/build.go
  tests/build/chains.go
  tests/build/jvm-build.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/integration-service/integration.go
Labels: lgtm, ok-to-test, approved

#290 fix: increatese timeout to prevent failure in CI
  tests/release/const.go
Labels: lgtm, approved

#284 feat: Translate installation bash scripts to magefiles
  README.md
  go.mod
  go.sum
  magefiles/installation/install.go
  magefiles/installation/oauth.go
  magefiles/magefile.go
  pkg/apis/kubernetes/client.go
  pkg/constants/constants.go
  pkg/utils/util.go
  scripts/e2e-openshift-ci.sh
  scripts/install-appstudio-e2e-mode.sh
  scripts/install-appstudio.sh
  scripts/provision-openshift-user.sh
  tests/build/build.go
  tests/release/const.go
Labels: approved

#293 fix(HACBS-1576): update component and snapshot labels
  pkg/utils/integration/controller.go
Labels: lgtm, approved

#295 fix: install: get infra-deployments branch, org
  magefiles/installation/install.go
Labels: lgtm, approved

#292 feat: build: pipeline-selector related tests
  cmd/loadTests.go
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/constants/constants.go
  pkg/framework/describe.go
  pkg/utils/build/hacbs.go
  pkg/utils/common/controller.go
  pkg/utils/has/controller.go
  tests/build/build.go
  tests/build/jvm-build.go
  tests/e2e-demos/e2e-demo.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#298 feat: e2e-demo print deployment when failed to deploy
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved

#300 fix: Add more verbose to installation scripts
  go.mod
  go.sum
  magefiles/utils.go
Labels: lgtm, approved

#299 fix: devfile_source.go - AfterAll for cleanup
  tests/has/devfile_source.go
Labels: lgtm, approved

#297 chore: disable the verbose output
  README.md
  cmd/e2e_test.go
  magefiles/magefile.go
  pkg/apis/github/repositories.go
  pkg/utils/build/sbom.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
  pkg/utils/tekton/controller.go
  templates/test_suite_cmd.tmpl
  tests/build/build.go
  tests/build/chains.go
  tests/build/jvm-build.go
  tests/e2e-demos/e2e-demo.go
  tests/integration-service/integration.go
  tests/release/release.go
Labels: lgtm, approved

#305 fix: Skip temporary multi component tests due an error on application-service cdq
  tests/e2e-demos/multi-component.go
Labels: lgtm, approved

#301 fix: sync timeouts of component ready and print component
  pkg/utils/has/controller.go
Labels: approved

#302 fix: use unique base branch in PaC build test
  pkg/apis/github/git.go
  pkg/utils/has/controller.go
  tests/build/build.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#303 fix: skip temporary container tests until STONE-336 issue is resolved
  tests/e2e-demos/config/config.go
  tests/e2e-demos/config/default.yaml
  tests/e2e-demos/config/types.go
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved

#304 fix: improve PR pairing
  magefiles/magefile.go
  magefiles/utils.go
Labels: lgtm, approved

#307 fix: increase timeout for pipelinerun
  tests/build/build.go
  tests/build/chains.go
Labels: lgtm, approved

#310 fix: Do not remove resources if specs failed for debuging
  tests/e2e-demos/e2e-demo.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: lgtm, approved

#308 feat: build - remove registry-auth
  pkg/utils/common/controller.go
  tests/build/build.go
Labels: lgtm, approved

#312 chore: Add owners for integration service test suite
  tests/integration-service/OWNERS
Labels: lgtm, approved

#309 fix(STONE-336): refactored e2e-demos.go to use integration service for Snapshot and SnapshotEnvironmentBinding creation
  README.md
  docs/DeveloperGenerateTest.md
  docs/LoadTests.md
  go.mod
  magefiles/installation/install.go
  magefiles/installation/oauth.go
  magefiles/magefile.go
  pkg/constants/constants.go
  pkg/framework/framework.go
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
  pkg/utils/tekton/controller.go
  tests/build/build.go
  tests/build/chains.go
  tests/cluster-registration/README.md
  tests/cluster-registration/clusters.go
  tests/e2e-demos/config/types.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
  tests/release/release.go
Labels: lgtm, ok-to-test, approved

#317 fix: STONE-421 fix misspelled "toolchain"
  magefiles/installation/install.go
Labels: lgtm, approved

#318 fix: build: skip CR deletion in case of failure
  tests/build/build.go
Labels: lgtm, approved

#315 fix: update build-service PaC test
  magefiles/magefile.go
  pkg/constants/constants.go
  pkg/utils/has/controller.go
Labels: approved

#319 fix: re-enable jvm-build-service test
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/utils/jvmbuildservice/controller.go
  tests/build/build.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#322 docs: remove outdated info
  README.md
Labels: lgtm, approved

#324 fix: STONE-442 Temporarily increase timeout for 'pipeline' SA creation.
  pkg/utils/common/controller.go
  tests/build/build.go
  tests/integration-service/integration.go
Labels: lgtm, approved
