Repository konflux-ci/e2e-tests, pull requests merged in 2023-12, with the labels that each got.

#920 fix: Add 1 sec wait before sending second build request and handle inivalid status message check
  tests/build/build.go
Labels: lgtm, approved

#922 fix: update the EC policy in happy_path_with_deployment
  tests/release/service/happy_path_with_deployment.go
Labels: lgtm, approved

#924 fix: RHTAPBUGS-1028: Add a struct to helper to retrigger pipelineruns in case of flaky registries
  pkg/clients/has/components.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/jvm-build.go
  tests/byoc/byoc.go
  tests/integration-service/integration.go
  tests/integration-service/namespace-backed-environments.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/service/happy_path.go
  tests/release/service/happy_path_with_deployment.go
  tests/remote-secret/component-annotation-image-pull-remote-secret.go
  tests/remote-secret/environments.go
  tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
  tests/rhtap-demo/rhtap-demo.go
Labels: approved, jira/valid-reference

#929 fix: RHTAPBUGS-1013: increase random string in branch names.
  tests/build/build.go
  tests/build/jvm-build.go
  tests/byoc/byoc.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, jira/valid-reference

#931 test: RHTAPBUGS-978 increase timeout of AwaitAttestationAndSignature
  tests/build/chains.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#936 fix: Change the test of tekton-results logs to meet the latest API change in tekton-results
  pkg/utils/pipeline/results.go
Labels: lgtm, approved

#933 chore: PLNSRVCE-1533: create a PaC on push job to update refs to the e2e-tests image used in build-definitions
  .tekton/update-build-definitions.yaml
Labels: lgtm, approved, jira/valid-reference

#941 fix: Skipping pac-related tests until RHTAPBUGS-1049 is fixed
  tests/build/build.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/rhtap-demo/config/scenarios.go
Labels: lgtm, approved

#943 fix: Revert skipping the pac-tests
  tests/build/build.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/rhtap-demo/config/scenarios.go
Labels: lgtm, approved

#889 chore: Added debug log for RHTAPBUGS-956 and also before other json.Unmarshals in build-tests
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/const.go
Labels: lgtm, approved

#919 feat(RHTAPREL-732): release: use pr values for RPA pipeline
  magefiles/magefile.go
  tests/release/pipelines/const.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
Labels: lgtm, approved

#946 fix: automatically skip the PaC-related test of integration service when there's an issue with sprayproxy server
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, do-not-merge/hold, approved

#942 chore: print out more logs for sprayproxy
  magefiles/magefile.go
Labels: lgtm, approved

#947 fix(RHTAP-1991): Daily-CI-test-does-not-produce-JSON-file
  tests/load-tests/ci-scripts/setup-cluster.sh
Labels: lgtm, approved

#949 fix: RHTAPBUGS-991: Do not run flaky tests in periodic jobs
  magefiles/magefile.go
Labels: lgtm, approved, jira/valid-reference

#937 feat(RHTAP-961): Calculating PV and PVC time stamp and adding those metrics to JSON
  cmd/loadTests.go
Labels: lgtm, approved

#923 fix(RHTAP-1892): time-skew-between-the-testing-machine-and-the-cluster
  cmd/loadTests.go
  tests/load-tests/ci-scripts/utility_scripts/measure-time-skew.sh
Labels: lgtm, approved

#951 fix: configuration of MP tests in CI
  magefiles/magefile.go
Labels: lgtm, approved

#953 feat: check workspace name is set correctly in the repository params
  go.mod
  go.sum
  pkg/clients/kubernetes/client.go
  pkg/clients/tekton/repository.go
  tests/build/build.go
Labels: lgtm, approved

#958 chore: Added debug log for rhtapbugs-1039
  pkg/clients/has/components.go
Labels: lgtm, approved

#935 fix(stoneintg): fix e2e-tests so buil PLR be reconciled on chains
  pkg/clients/integration/pipelineruns.go
  tests/integration-service/const.go
  tests/integration-service/integration.go
  tests/integration-service/namespace-backed-environments.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved

#945 fix: [RHTAPBUGS-996] Increase timeout
  tests/build/build.go
Labels: lgtm, approved

#957 fix(RHTAPREL-732): fix magefile for release-service-catalog
  magefiles/magefile.go
Labels: lgtm, approved

#959 chore: update IC list
  pipelines/interrupt_catcher/cm_people_list.yaml
Labels: lgtm, approved

#898 fix: release clean up code
  tests/release/const.go
  tests/release/pipelines/const.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/service/const.go
  tests/release/service/happy_path.go
  tests/release/service/happy_path_with_deployment.go
  tests/release/service/missing_release_plan_and_admission.go
  tests/release/service/release_plan_owner_ref.go
Labels: lgtm, approved

#950 fix: issues of registering pac server in sprayproxy
  magefiles/magefile.go
  pkg/clients/sprayproxy/sprayproxy.go
Labels: lgtm, approved

#962 fix: Remove sandbox logging
  pkg/sandbox/sandbox.go
Labels: lgtm, approved

#934 feat(STONEINTG-702): add tests for integration pipeline re-runs
  go.mod
  pkg/clients/integration/snapshots.go
  tests/integration-service/const.go
  tests/integration-service/integration.go
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#932 feat(RHTAPREL-740): add fbc hotfix test case
  tests/release/const.go
  tests/release/pipelines/fbc_release.go
  tests/release/releaseLib.go
Labels: lgtm, approved

#961 fix: release-service-catalog CI config
  magefiles/magefile.go
Labels: lgtm, approved

#963 fix: fix the issue of cleanup invalid pac servers
  magefiles/magefile.go
Labels: lgtm, approved

#964 chore: add OWNERS for release-pipelines-suite
  tests/release/pipelines/OWNERS
Labels: lgtm, approved

#955 test: RHTAPBUGS-978 increase timeout of component deletion from 10min to 15min
  pkg/clients/has/components.go
  tests/byoc/byoc.go
  tests/remote-secret/environments.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#965 fix: refer to correct PLR sha in case of PLR retry
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved

#956 chore: cleanup Gitops repos
  magefiles/magefile.go
Labels: lgtm, approved

#960 test: verify multiplatform cleanup
  tests/build/multi-platform.go
Labels: lgtm, approved

#967 fix(STONEINTG-702): remove check for successful Snapshot after re-run
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#973 fix: update the EC policy for push_to_external_registry
  tests/release/pipelines/push_to_external_registry.go
Labels: lgtm, approved

#968 chore(RHTAPREL-732): turn off release-pipelines tests
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
Labels: lgtm, approved

#974 fix: Add email to the sandobx usersignups
  go.mod
  go.sum
  pkg/sandbox/sandbox.go
Labels: lgtm, approved

#948 feat(RHTAPREL-751): update README.md for release test suite
  tests/release/README.md
  tests/release/pipelines/README.md
  tests/release/service/README.md
Labels: lgtm, approved

#976 fix: add credentials settings for FBC tests
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved

#910 feat(RHTAPREL-739): add e2e-tests for RP and RPA reconcilation
  go.mod
  go.sum
  tests/release/const.go
  tests/release/service/release_plan_and_admission_matched.go
Labels: lgtm, approved

#979 fix: Use eventually when updating component
  tests/build/build.go
Labels: lgtm, approved

#980 fix(RHTAPBUGS-980): increase timeout and internal in NBE case
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#981 fix: increase timeout for NPE case
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#985 fix(RHTAPBUGS-980): don't retry for the unrecoverable error
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved
