Repository konflux-ci/e2e-tests, pull requests merged in 2023-08, with the labels that each got.

#664 fix: RHTAPBUGS-536 Wait for branch to exist
  pkg/apis/github/git.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#582 test: add spi oauth test flow
  magefiles/installation/install.go
  scripts/spi-e2e-setup.sh
  tests/README.md
  tests/spi/README.md
  tests/spi/oauth.go
Labels: lgtm, approved

#642 chore: Add Stage Api Load Test
  .github/workflows/loadtest.yaml
  cmd/loadTests.go
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/framework/framework.go
  pkg/utils/loadtests/controller.go
  tests/load-tests/ci-scripts/merge-json.sh
  tests/load-tests/run-stage.sh
Labels: lgtm, approved

#669 fix: temporary disable oauth test
  tests/spi/oauth.go
Labels: lgtm, approved

#670 fix: RHTAPBUGS-541 increasing timeout when checking if taskrun is complete
  tests/spi/quay-imagepullsecret-usage.go
Labels: lgtm, approved

#671 feat(RHTAP-1335): Archive results for stage load test CI
  .github/workflows/loadtest.yaml
  tests/load-tests/ci-scripts/stage/collect-results.sh
Labels: lgtm, approved

#663 feat(load-test): sort output pipelineruns CSV by SucceededDuration column
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
Labels: lgtm, approved

#519 fix(github-actions): bump deprecated versions of GH actions
  .github/workflows/PR.yaml
  .github/workflows/build.yaml
  .github/workflows/conventional-commits.yaml
Labels: bug, lgtm, approved

#644 feat: [RHTAP-1078] Refactor integration controller code
  pkg/framework/framework.go
  pkg/utils/common/snapshot_environment_bindings.go
  pkg/utils/common/test_status.go
  pkg/utils/gitops/space_requests.go
  pkg/utils/has/snapshotenvironmentbindings.go
  pkg/utils/integration/controller.go
  pkg/utils/integration/integration_test_scenarios.go
  pkg/utils/integration/pipelineruns.go
  pkg/utils/integration/snapshots.go
  pkg/utils/release/releases.go
  tests/byoc/byoc.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/integration-service/integration.go
  tests/release/release.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#678 chore(ci): add workaround for new OSP ver
  .tekton/pull-request.yaml
  .tekton/push.yaml
Labels: lgtm, approved

#676 fix: count the application type purls in test
  tests/build/build_templates.go
Labels: lgtm, approved

#648 feat: Added test to check if repo contains symlink
  tests/build/build_templates.go
  tests/build/const.go
Labels: lgtm, approved

#662 feat: adding release negative 3 e2e-tests and updating them to README
  go.mod
  go.sum
  tests/release/README.md
  tests/release/const.go
  tests/release/neg-missing-releaseplanadmission.go
  tests/release/neg-missing-releasestrategy.go
  tests/release/neg-missingreleaseplan.go
  tests/release/release.go
Labels: lgtm, approved

#600 feat: Store logs collected in artifacts folder in reportportal
  pkg/framework/custom_junit_reporter.go
Labels: lgtm, approved

#683 fix: set rhtap-demo release cr to 15 minutes timeout.
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#672 fix: delete original pipelinerun
  tests/build/jvm-build.go
Labels: lgtm, approved

#685 chore: temporarily disable release-pyxis test
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#681 chore: simplify e2e-demo tests and config
  cmd/e2e_test.go
  go.mod
  go.sum
  magefiles/magefile.go
  templates/test_suite_cmd.tmpl
  tests/e2e-demos/README.md
  tests/e2e-demos/config/config.go
  tests/e2e-demos/config/default.yaml
  tests/e2e-demos/config/scenarios.go
  tests/e2e-demos/config/types.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
Labels: lgtm, approved

#682 test: SVPI-557 re-enable and refactor remote-secret test with authz in mind
  pkg/apis/github/git.go
  pkg/utils/common/rbac.go
  pkg/utils/common/secret.go
  pkg/utils/common/service_account.go
  pkg/utils/spi/controller.go
  tests/build/build_templates.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/rhtap-demo/rhtap-demo.go
  tests/spi/link-secret-sa.go
  tests/spi/quay-imagepullsecret-usage.go
  tests/spi/remote-secret.go
Labels: lgtm, approved

#679 fix: re-enable spi oauth test and improve logging
  tests/spi/oauth.go
Labels: lgtm, approved

#592 feat: add tests for new build service annotations
  go.mod
  go.sum
  pkg/utils/build/quay.go
  pkg/utils/has/components.go
  tests/build/build.go
Labels: lgtm, approved

#687 feat(HACBS-2400): Chains secret from OpenShift Pipelines
  pkg/constants/constants.go
  pkg/utils/tekton/controller.go
  tests/build/chains.go
  tests/enterprise-contract/contract.go
Labels: lgtm

#692 chore: bump release pipeline version in pyxis test
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#693 fix: Improve error message matching
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#691 feat(RHTAP-1421): Include tapa tool in collect-resources step of load test CI
  .gitignore
  tests/load-tests/ci-scripts/collect-results.sh
Labels: lgtm, approved

#675 feat: [RHTAP-1282] Refactor jvmbuildservice controller code
  pkg/framework/framework.go
  pkg/utils/jvmbuildservice/artifact_builds.go
  pkg/utils/jvmbuildservice/caches.go
  pkg/utils/jvmbuildservice/controller.go
  pkg/utils/jvmbuildservice/dependency_builds.go
  pkg/utils/jvmbuildservice/jbs_configs.go
  pkg/utils/jvmbuildservice/rebuilt_artifacts.go
  tests/build/jvm-build.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#674 fix(RHTAP-1416): Add PR number to USER_PREFIX to avoid naming collisions while running multiple PRs in parallel
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/load-test.sh
  tests/load-tests/ci-scripts/max-concurrency/load-test.sh
  tests/load-tests/ci-scripts/user-prefix.sh
Labels: bug, lgtm, approved

#694 test: RHTAPBUGS-556 check first errorBuffer before buffer on spi access control e2e test
  tests/build/build.go
  tests/spi/access-control.go
Labels: lgtm, approved

#697 feat(load-test): Switch tapa tool to CSV output.
  tests/load-tests/ci-scripts/collect-results.sh
Labels: lgtm, approved

#661 feat(RHTAP-1018): load test measure how long the app test took
  cmd/loadTests.go
  docs/LoadTests.md
  pkg/utils/has/components.go
  tests/load-tests/load-tests-example.json
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#699 chore: merge e2e-demo and rhtap-demo
  cmd/e2e_test.go
  pkg/framework/describe.go
  pkg/utils/util.go
  tests/e2e-demos/README.md
  tests/e2e-demos/e2e-demo.go
  tests/rhtap-demo/README.md
  tests/rhtap-demo/config/scenarios.go
  tests/rhtap-demo/config/types.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#705 fix: deletecollection "as developer" workaround
  tests/byoc/byoc.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#701 feat: add ginkgolinter
  .golangci.yml
  tests/build/build.go
Labels: lgtm, approved

#706 test(HACBS-2469): create test for releaseplan adapter
  tests/release/README.md
  tests/release/const.go
  tests/release/e2e-test-releaseplan-owner-ref.go
Labels: lgtm, approved

#709 fix(load-test): Do not show respective progress bars when not waiting for pipelines, deployments or integration tests
  cmd/loadTests.go
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: bug, lgtm, approved

#696 fix: Wait for atts/sigs in build template tests
  tests/build/build_templates.go
Labels: lgtm, approved

#700 feat(RHTAP-1337): Properly cleanup in stage
  cmd/loadTests.go
  pkg/utils/has/componentdetectionqueries.go
Labels: lgtm, approved

#710 feat(RHTAP-1415): Make it possible to specify output directory for load test
  cmd/loadTests.go
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/load-test.sh
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#712 chore: add 2 additional failure tests for SEB
  tests/integration-service/integration.go
Labels: lgtm, approved

#680 fix: Moved the proxyplugin creation to BeforeAll section
  tests/build/build_templates.go
Labels: lgtm, approved

#651 feat: [RHTAP-1197] Refactor spi controller code
  pkg/framework/framework.go
  pkg/utils/spi/access_checks.go
  pkg/utils/spi/access_token_bindings.go
  pkg/utils/spi/access_tokens.go
  pkg/utils/spi/controller.go
  pkg/utils/spi/file_content_requests.go
  pkg/utils/spi/remote_secrets.go
  pkg/utils/spi/uploads.go
Labels: lgtm, approved

#702 fix: spi: repository name typo
  tests/spi/quay-imagepullsecret-usage.go
Labels: lgtm, approved

#713 feat: store results of JVM Builds
  cmd/loadTests.go
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/apis/vcluster/vcluster.go
  pkg/utils/common/secret.go
  pkg/utils/has/components.go
  pkg/utils/integration/pipelineruns.go
  pkg/utils/jvmbuildservice/caches.go
  pkg/utils/o11y/controller.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/pipelines.go
  pkg/utils/util.go
  tests/build/build.go
  tests/build/jvm-build.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#720 fix: replace deprecated annotations
  pkg/constants/constants.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#722 fix: move proxyplugin creation and deletion
  tests/build/build_templates.go
Labels: lgtm, approved

#719 feat: prepare for e2e jobs in remotesecret and spi repos
  cmd/e2e_test.go
  magefiles/magefile.go
  pkg/framework/describe.go
  pkg/framework/framework.go
  pkg/utils/remotesecret/controller.go
  pkg/utils/remotesecret/remote_secrets.go
  tests/remotesecret/remotesecret.go
Labels: lgtm, approved

#714 feat: dump logs on failure
  pkg/framework/failure_report.go
  pkg/framework/failure_report_test.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/build/jvm-build.go
  tests/byoc/byoc.go
  tests/cluster-registration/clusters.go
  tests/enterprise-contract/contract.go
  tests/integration-service/integration.go
  tests/o11y/o11y-deployments.go
  tests/o11y/o11y-pipelinerun.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/release/e2e-test-releaseplan-owner-ref.go
  tests/release/neg-missing-releaseplanadmission.go
  tests/release/neg-missing-releasestrategy.go
  tests/release/neg-missingreleaseplan.go
  tests/remotesecret/remotesecret.go
  tests/rhtap-demo/rhtap-demo.go
  tests/spi/get-file-content.go
  tests/spi/link-secret-sa.go
  tests/spi/oauth.go
  tests/spi/quay-imagepullsecret-usage.go
  tests/spi/token-upload-k8s.go
  tests/spi/token-upload-rest-endpoint.go
Labels: lgtm, approved

#715 feat(RHTAP-1336): Collect-monitoring-data-from-the-OCP-Prometheus
  .github/workflows/loadtest.yaml
  tests/load-tests/ci-scripts/stage/collect-results.sh
Labels: lgtm, approved

#723 refactor: tekton.VerifyEnterpriseContract
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/pipelines.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/enterprise-contract/const.go
  tests/enterprise-contract/contract.go
Labels: approved

#684 feat: [RHTAP-1406] Adjusting failed pipelineRun log storing function
  pkg/framework/custom_junit_reporter.go
  pkg/logs/log_naming.go
  pkg/logs/logs.go
  pkg/utils/has/components.go
  pkg/utils/tekton/pipelines.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#728 fix: update cypress image
  tests/spi/oauth.go
Labels: lgtm, approved

#724 feat: test that EC Task is run in Release pipeline
  tests/release/const.go
  tests/release/e2e-test-default-bundle.go
Labels: approved

#721 chore: Disable / Enable progress bar in load test
  cmd/loadTests.go
  tests/load-tests/run.sh
Labels: lgtm, ok-to-test, approved

#717 chore: change new tests to push type tests
  pkg/utils/loadtests/controller.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#730 fix: wrong component revision
  tests/build/const.go
Labels: lgtm, approved

#732 feat: Allow EC pipeline tests from fork PR
  pkg/apis/github/pull_request.go
  tests/build/chains.go
Labels: lgtm, approved

#727 fix(load-test): Try to collect as much results as possible without failing if files not found.
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
Labels: lgtm, approved

#733 fix: use custom label for ec pipelines
  tests/build/chains.go
Labels: lgtm, approved

#718 feat(RHTAP-1338): Add-random-prefix-to-all-resource-names
  cmd/loadTests.go
  tests/load-tests/run.sh
Labels: lgtm, approved

#739 fix: skip spi skopeo test until fixed
  tests/spi/quay-imagepullsecret-usage.go
Labels: lgtm, approved

#689 chore: enable release-pyxis test again
  pkg/constants/constants.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#737 fix: move ec-pipelines label
  tests/build/chains.go
Labels: lgtm, approved

#736 fix: updated owners list for integration-service
  tests/integration-service/OWNERS
Labels: lgtm, approved

#704 feat: Few more interesting queries to track
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/cluster_read_config.yaml
Labels: lgtm, approved
