Repository konflux-ci/e2e-tests, pull requests merged in 2023-06, with the labels that each got.

#506 feat: extend pyxi's test to include SBOM validation
  pkg/utils/release/controller.go
  pkg/utils/release/sbom.go
  tests/release/const.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/release/release.go
Labels: lgtm, approved

#547 feat: Adding README.txt for release e2e-tests
  tests/release/README.md
Labels: lgtm, approved

#555 feat(RHTAP-969): Make it possible to run basic or advanced pipeline builds in load test
  cmd/loadTests.go
  pkg/utils/has/controller.go
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/load-tests-example.json
  tests/load-tests/run.sh
Labels: lgtm, approved

#557 chore: add pmacik to root OWNERS file
  OWNERS
Labels: lgtm, approved

#560 feat(RHTAP-970): Create a load test that tracks max concurrency with builds below given threshold
  cmd/loadTests.go
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/ci-scripts/max-concurrency/load-test.sh
  tests/load-tests/run-max-concurrency.sh
Labels: lgtm, approved

#556 chore: update release-service version in go.mod
  go.mod
  go.sum
Labels: lgtm, approved

#537 fix: RHTAPBUGS-257 Increase level of logging
  cmd/e2e_test.go
  pkg/sandbox/sandbox.go
Labels: lgtm, approved

#484 feat: tests for using SPI in JVM Build Service
  tests/build/jvm-build.go
Labels: approved

#544 feat(RHTAP-963): Also collect some monitoring data
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/cluster_read_config.yaml
Labels: lgtm, approved

#563 fix: set StandingAttribution label in ReleasePlans
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
Labels: approved

#535 feat: retry logic for build pipelineruns
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/utils/common/pod.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  pkg/utils/tekton/pipelines.go
  pkg/utils/util.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/build/const.go
  tests/build/jvm-build.go
  tests/byoc/byoc.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/enterprise-contract/contract.go
  tests/integration-service/integration.go
  tests/mvp-demo/mvp-demo.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#500 test: RHTAP-814 update e2e-tests to use CDQ in cases when git ref is not known
  pkg/utils/has/controller.go
  pkg/utils/release/controller.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/integration-service/integration.go
  tests/mvp-demo/mvp-demo.go
  tests/release/const.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#567 fix: RHTAPBUGS-398: RetryOnConflict when update a component
  pkg/utils/has/controller.go
Labels: approved, jira/valid-reference

#569 feat(load-test): Split output for max-concurrency load test per step and include cluster metrics
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/run-max-concurrency.sh
Labels: lgtm, approved

#573 fix: Skip frontend advanced checks in e2e-demos due huge memory needs
  tests/e2e-demos/multi-component.go
Labels: lgtm, approved

#554 feat(HACBS-2222): update release pipeline versions
  pkg/constants/constants.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, do-not-merge/hold, approved

#574 fix: RHTAPBUGS-257: Improve kubernetes clients by creating the rest clients with bearer token
  cmd/e2e_test.go
  pkg/apis/kubernetes/client.go
  pkg/sandbox/sandbox.go
  tests/byoc/byoc.go
Labels: approved, jira/valid-reference

#566 fix: Remove duplicated code and use "Succeed()" for concise code
  tests/integration-service/integration.go
Labels: lgtm, approved

#575 feat(HACBS-2055): update release pipeline tags
  pkg/constants/constants.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#579 fix: RHTAPBUGS-202: skip tekton results validation due product issue. Is blocking part of our tests to merge PRs
  tests/build/build_templates.go
  tests/release/e2e-test-default-with-deployment.go
Labels: approved, jira/valid-reference

#548 feat: add pruning e2e-test
  README.md
  magefiles/installation/install.go
  pkg/constants/constants.go
  pkg/utils/build/image.go
  pkg/utils/build/sbom.go
  tests/build/build.go
Labels: lgtm, approved

#583 fix(STONEINTG-401): remove check for integration bundle
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#584 feat(HACBS-2216): Removem chains-ca-cert support
  tests/build/chains.go
Labels: lgtm, approved

#568 feat: e2e test for moving from advance to simple build
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#586 fix: build: remove inappropriate label
  tests/build/build.go
Labels: lgtm, approved

#572 feat(RHTAP-979): Add possibility in load test to tweak tekton performance
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/ci-scripts/setup-cluster.sh
  tests/load-tests/ci-scripts/tekton-performance/update-tekton-config-performance.yaml
  tests/load-tests/cluster_read_config.yaml
  tests/load-tests/run-max-concurrency.sh
Labels: lgtm, approved

#589 fix: Remove has suites due duplications. All appservice e2e are covered in e2e-demo folder tests
  cmd/e2e_test.go
  docs/LabelsNaming.md
  magefiles/magefile.go
  tests/has/README.md
  tests/has/const.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: lgtm, approved

#482 fix: [RHTAPBUGS-101] Linked pull secret to SA + adjusted dummy credentials…
  pkg/framework/framework.go
  pkg/utils/common/secret.go
  tests/build/build.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#565 test: PLNSRVCE-1311: Access ui tekton results data using proxyplugin
  pkg/apis/kubernetes/client.go
  pkg/framework/framework.go
  pkg/utils/common/proxy_plugin.go
  tests/build/build_templates.go
Labels: lgtm, needs-ok-to-test, approved, jira/valid-reference

#585 feat: use automatically created image repos
  go.mod
  go.sum
  pkg/utils/jvmbuildservice/controller.go
  tests/build/jvm-build.go
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#597 chore(HACBS-2304): bump release pipeline versions
  pkg/constants/constants.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#591 feat(STONEINTG-467): add test case for testing v1beta1 ITS
  pkg/apis/kubernetes/client.go
  pkg/utils/integration/controller.go
  tests/integration-service/integration.go
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#595 fix(load-test): Stop creating redhat-appstudio-registry-pull-secret in user namespace
  cmd/loadTests.go
  docs/LoadTests.md
  pkg/constants/constants.go
  pkg/utils/util.go
  tests/load-tests/ci-scripts/load-test.sh
  tests/load-tests/ci-scripts/max-concurrency/load-test.sh
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#596 chore: remove chapter 1 from mvp-demo, mvp-demo -> rhtap-demo
  README.md
  cmd/e2e_test.go
  go.mod
  go.sum
  magefiles/magefile.go
  pkg/framework/describe.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  pkg/utils/jvmbuildservice/controller.go
  pkg/utils/util.go
  tests/build/jvm-build.go
  tests/integration-service/integration.go
  tests/mvp-demo/README.md
  tests/mvp-demo/mvp-demo.go
  tests/rhtap-demo/README.md
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#609 feat(HACBS-2310): add RoleBindings for Release PLR ClusterRole
  pkg/utils/release/controller.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#607 fix(load-test): Archive output after metrics has been added not before
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
Labels: lgtm, approved

#602 test: Change tests according to image controller always deletes component image repository
  pkg/constants/constants.go
  pkg/utils/has/controller.go
  tests/build/build.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#611 test: RHTAPBUGS-440 change branch name input on CreateRef in e2e-test-default-bundle and e2e-test-default-with-deployment tests
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
Labels: lgtm, approved

#601 test: RHTAPBUGS-426 increase timeout when checking if release is marked as deployed on e2e-test-default-with-deployment test
  tests/release/const.go
  tests/release/e2e-test-default-with-deployment.go
Labels: lgtm, approved

#610 feat(RHTAP-1012): Enable pprof for tekton controller in load test and collect profiling data in CI
  tests/load-tests/.gitignore
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/load-test.sh
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/ci-scripts/max-concurrency/load-test.sh
  tests/load-tests/ci-scripts/setup-cluster.sh
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#570 fix: RHTAPBUGS-257 Add -v in ginkgo command
  cmd/e2e_test.go
  magefiles/magefile.go
Labels: lgtm, approved

#606 feat: RHTAP-1058: Refactor Application Service code
  cmd/loadTests.go
  pkg/framework/framework.go
  pkg/utils/has/applications.go
  pkg/utils/has/componentdetectionqueries.go
  pkg/utils/has/components.go
  pkg/utils/has/controller.go
  pkg/utils/has/factory.go
  pkg/utils/has/snapshotenvironmentbindings.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/jvm-build.go
  tests/byoc/byoc.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/integration-service/integration.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, jira/valid-reference

#542 fix: Check image controller annotations in component when image generate is set
  pkg/utils/build/quay.go
  pkg/utils/has/components.go
Labels: lgtm, approved

#603 docs: Improve UX when running e2e as a dev
  .gitignore
  README.md
  default.env
Labels: approved

#614 feat: RHTAP-1058: Unify all gitops CRUD operations under one gitops factory
  pkg/framework/framework.go
  pkg/utils/common/route.go
  pkg/utils/gitops/controller.go
  pkg/utils/gitops/deploymenttargetclaims.go
  pkg/utils/gitops/deploymenttargetclasses.go
  pkg/utils/gitops/deploymenttargets.go
  pkg/utils/gitops/environments.go
  pkg/utils/gitops/factory.go
  pkg/utils/gitops/gitopsdeployments.go
  pkg/utils/has/components.go
  pkg/utils/integration/controller.go
  tests/byoc/byoc.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/integration-service/integration.go
  tests/release/e2e-test-default-with-deployment.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, jira/valid-reference

#613 feat(RHTAP-1077): Enable debugging and collecting logs for kube scheduler
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/load-test.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#618 feat: HACBS-2315: Remove outdated EC dependency
  tests/release/release.go
Labels: lgtm, approved, jira/valid-reference
