Repository konflux-ci/e2e-tests, pull requests merged in 2023-04, with the labels that each got.

#396 fix: out-of-date load test
  cmd/loadTests.go
  docs/LoadTests.md
  tests/load-tests/.gitignore
  tests/load-tests/clear.sh
  tests/load-tests/loadtest.go
  tests/load-tests/run.sh
Labels: lgtm, ok-to-test, approved

#420 fix(STONEINTG-233): Remove sanity checks to unblock e2e tests
  tests/build/build_templates.go
Labels: lgtm, approved

#424 fix: Enabling sbom check in the build-templates-e2e tests
  tests/build/build_templates.go
Labels: lgtm, approved

#425 fix: DEVHAS-254: Disable e2e for private repositories
  go.sum
  pkg/utils/has/controller.go
  tests/has/devfile_private_source.go
Labels: lgtm, approved, jira/valid-reference

#423 feat: Avoid secondary rate limits in e2e-tests
  go.mod
  go.sum
  magefiles/magefile.go
  pkg/apis/github/client.go
  pkg/utils/common/controller.go
Labels: lgtm, approved

#428 fix: release: move fw init to BeforeAll
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#426 fix: Remove webhooks from redhat-appstudio/hacbs-test-project
  magefiles/magefile.go
Labels: approved

#431 test: added pipeline label in build_templates tests
  tests/build/build_templates.go
Labels: lgtm, approved

#432 test: RHTAPBUGS-34 added ginkgo flag --output-interceptor-mode=none
  magefiles/magefile.go
Labels: lgtm, approved

#414 test(STONEO11Y-32): pipeline network egress e2e test
  pkg/utils/o11y/controller.go
  pkg/utils/tekton/controller.go
  tests/o11y/const.go
  tests/o11y/o11y.go
Labels: lgtm, approved

#409 feat: STONEINTG-316: add integration-service negative scenario when integration test fails
  tests/integration-service/integration.go
Labels: lgtm, approved, jira/valid-reference

#419 feat(STONEINTG-233): add surface checks back into e2e tests
  pkg/utils/build/hacbs.go
  tests/build/build_templates.go
Labels: lgtm, approved

#434 feat: add new spi test suite
  cmd/e2e_test.go
  go.sum
  pkg/framework/describe.go
  pkg/utils/spi/controller.go
  tests/spi/const.go
  tests/spi/spi.go
Labels: lgtm, approved

#440 fix: build: add container image field to PaC comp
  tests/build/build.go
Labels: lgtm, approved

#413 fix: DEVHAS-305: Add different scenario’s to multiple components testing
  pkg/utils/has/controller.go
  pkg/utils/util.go
  tests/e2e-demos/config/types.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: approved, jira/valid-reference

#439 fix: RHTAPBUGS-34 return the error instead of fatal log it
  pkg/utils/pipeline/results.go
Labels: lgtm, approved

#437 feat: Change related to openshift-ci on boarding to image-controller repo
  magefiles/magefile.go
Labels: lgtm, approved

#387 test: STONE-664 keep/archive failed pipelineruns
  pkg/utils/tekton/pipelines.go
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved

#445 fix: Fix logic in setRequiredEnvVars for image-controller jobs
  magefiles/magefile.go
Labels: lgtm, approved

#446 test: Add test case for show-sbom task
  pkg/utils/tekton/controller.go
  tests/build/build_templates.go
Labels: lgtm, approved

#447 fix: improve mvp-demo test
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/integration-service/integration.go
  tests/mvp-demo/README.md
  tests/mvp-demo/mvp-demo.go
  tests/release/release.go
Labels: lgtm, approved

#455 feat: Make SPI service providers configurable from env variables
  scripts/spi-e2e-setup.sh
Labels: lgtm, needs-ok-to-test, approved

#448 fix: Run pac-build tests for image controller repo
  magefiles/magefile.go
  pkg/constants/constants.go
  pkg/utils/has/controller.go
  pkg/utils/util.go
Labels: lgtm, approved

#459 fix: refresh component prior to error log to obtain useful status info
  pkg/utils/has/controller.go
Labels: lgtm, approved

#460 fix: mvp-demo: unique component name
  pkg/constants/constants.go
  pkg/utils/release/controller.go
  tests/mvp-demo/README.md
  tests/mvp-demo/mvp-demo.go
  tests/release/const.go
Labels: lgtm, approved

#421 feat: added cleanup of generated quay repos and robot accounts
  .github/workflows/PR.yaml
  Makefile
  go.mod
  go.sum
  magefiles/magefile.go
  magefiles/utils.go
  magefiles/utils_test.go
Labels: lgtm, approved

#438 feat: DEVHAS-234: Add 2 scenarios to e2e-demos
  tests/e2e-demos/config/default.yaml
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved, jira/valid-reference

#468 fix: refresh application prior to error log to obtain useful status info
  pkg/utils/has/controller.go
Labels: lgtm, approved

#464 chore: Add more spi tests
  pkg/utils/spi/controller.go
  tests/spi/README.md
  tests/spi/const.go
  tests/spi/get-file-content.go
  tests/spi/quay-imagepullsecret-usage.go
Labels: lgtm, approved

#470 fix(STONEINTG-248): don't specify environment for ITS
  pkg/utils/integration/controller.go
Labels: lgtm

#472 feat: use user token to create resources
  cmd/loadTests.go
Labels: lgtm, approved

#457 feat(RHTAP-623): load test to generate json file with all the results
  cmd/loadTests.go
  tests/load-tests/load-tests-example.json
Labels: lgtm, approved

#477 fix: RHTAPBUGS-197:skip pyxis tests due failures
  go.mod
  go.sum
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved, jira/valid-reference

#474 fix(keycloak.go): panic when response is nil
  pkg/sandbox/keycloak.go
Labels: bug, lgtm, approved

#476 feat: support for (HACBS_)?TEST_OUTPUT result name
  pkg/constants/constants.go
  pkg/utils/build/task_results.go
  tests/build/build_templates.go
  tests/build/chains.go
Labels: lgtm, approved

#481 fix: Point pac to openshift-pipelines namespace
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#483 fix: revert e2e namespace to pipeline-as-code
  tests/build/build.go
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#463 feat: add test case 1885
  cmd/e2e_test.go
  pkg/framework/describe.go
  pkg/utils/tekton/pipelines.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/enterprise-contract/README.md
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#461 feat(HACBS-1777): adapt test to run for latest Release refactor
  go.mod
  go.sum
  tests/mvp-demo/mvp-demo.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/release/release.go
Labels: lgtm, approved

#485 fix: set integration tests as pending temporarily
  tests/integration-service/integration.go
Labels: approved

#488 fix: just check for end fail release, lose intermediate is progressing check
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved
