Repository konflux-ci/e2e-tests, pull requests merged in 2023-10, with the labels that each got.

#797 fix: RHTAPBUGS-845: Skip python deploy to unblock prs merging
  tests/rhtap-demo/config/scenarios.go
Labels: lgtm, approved, jira/valid-reference

#798 fix: RHTAPBUGS-257 Change context.TODO() to context.Background()
  pkg/utils/gitops/environments.go
  pkg/utils/has/applications.go
  pkg/utils/spi/access_checks.go
  pkg/utils/spi/access_token_bindings.go
Labels: lgtm, approved

#800 chore: temporarily disable PaC test cases
  magefiles/magefile.go
  tests/build/build.go
  tests/rhtap-demo/config/scenarios.go
Labels: lgtm, approved

#794 test: SVPI-558 - test all the options of the auth of remote secret target deployment
  cmd/loadTests.go
  docs/DeveloperGenerateTest.md
  magefiles/sprayproxy.go
  pipelines/interrupt_catcher/README.md
  pkg/constants/constants.go
  pkg/utils/integration/integration_test_scenarios.go
  pkg/utils/integration/pipelineruns.go
  pkg/utils/integration/snapshots.go
  pkg/utils/loadtests/controller.go
  pkg/utils/remotesecret/remote_secrets.go
  pkg/utils/util.go
  tests/integration-service/README.md
  tests/integration-service/namespace-backed-environments.go
  tests/remotesecret/kubeconfig-auth.go
  tests/remotesecret/service-account-auth.go
  tests/remotesecret/target-current-namespace.go
Labels: lgtm, approved

#796 fix: [RHTAP-1704] print logs to files instead of stdout
  pkg/framework/failure_report.go
  pkg/logs/utils.go
  pkg/utils/common/pod.go
Labels: lgtm, approved

#799 feat: Create a new suite for releasepipelines tests
  magefiles/magefile.go
  tests/release/pipelines/README.md
Labels: lgtm, approved

#793 fix: release controller looking for application in release tests
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/release/e2e-test-releaseplan-owner-ref.go
  tests/release/neg-missing-releaseplanadmission.go
  tests/release/neg-missing-releasestrategy.go
  tests/release/neg-missingreleaseplan.go
  tests/release/release.go
Labels: lgtm, approved

#805 fix: handle spray proxy error with alert
  go.mod
  go.sum
  magefiles/magefile.go
  magefiles/utils.go
  pkg/clients/slack/slack.go
  pkg/constants/constants.go
  tests/build/build.go
  tests/rhtap-demo/config/scenarios.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#809 fix: build: validating PaC checks status
  pkg/apis/github/pull_request.go
  tests/build/build.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#810 fix: remove the exclude assert
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#811 fix: JVM test failures
  pkg/constants/constants.go
Labels: lgtm, approved

#806 feat: To detect KPI, let's use whole workload as deployment might take tenths of seconds as well
  cmd/loadTests.go
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/run-max-concurrency.sh
Labels: lgtm, approved

#817 fix: compatibility with OSP 1.12
  tests/build/build.go
Labels: lgtm, approved

#804 feat(STONEINTG-530): Making NBE more robust
  go.mod
  go.sum
  pkg/utils/gitops/deploymenttargets.go
  pkg/utils/gitops/gitopsdeployments.go
  pkg/utils/gitops/space.go
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#821 fix: Python command does not exist
  tests/load-tests/run-max-concurrency.sh
Labels: lgtm, approved

#824 fix: use CheckRuns for validating PaC build result
  pkg/apis/github/pull_request.go
  tests/build/build.go
Labels: lgtm, approved

#813 fix(RHTAPBUGS-823): wait for Snapshot to succeed
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#780 fix: update the root OWNERS
  OWNERS
Labels: lgtm, approved

#815 test: (SVPI-632, SVPI-633) add remote secrets environments tests
  go.sum
  pkg/utils/remotesecret/remote_secrets.go
  pkg/utils/util.go
  tests/remotesecret/environments.go
Labels: lgtm, approved

#825 fix: fix remote secret suite in environment test
  tests/remotesecret/environments.go
Labels: lgtm, approved

#802 feat: check Chains signing secret is present
  pkg/constants/constants.go
  tests/build/chains.go
Labels: lgtm, approved

#707 docs: documented pr review and approve in e2e-tests
  README.md
Labels: lgtm, approved

#823 fix(STONEINTG-530): prevent index out of range error before condition is…
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#801 chore: Add Push per action metrics on stage
  .github/workflows/loadtest.yaml
  cmd/loadTests.go
  go.mod
  go.sum
  pkg/utils/loadtests/controller.go
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#829 fix(RHTAPBUGS-883): make sure revision is set
  tests/build/build_templates.go
Labels: lgtm, approved

#792 chore: remove the unneccessary code
  tests/build/build.go
Labels: lgtm, approved

#831 fix: RHTAPBUGS-540 increase the timeout another 30sec
  tests/byoc/byoc.go
  tests/remotesecret/environments.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#830 chore: enabling push metrics on openshift ci
  .github/workflows/loadtest.yaml
  OWNERS
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#816 docs: RHTAPBUGS-873 update doc about E2E tests
  README.md
  cmd/e2e_test.go
  docs/DeveloperGenerateTest.md
  docs/InvestigatingCIFailures.md
  pipelines/interrupt_catcher/README.md
  tests/README.md
  tests/release/pipelines/README.md
  tests/remote-secret/environments.go
  tests/remote-secret/kubeconfig-auth.go
  tests/remote-secret/service-account-auth.go
  tests/remote-secret/target-current-namespace.go
  tests/rhtap-demo/README.md
Labels: lgtm, approved

#836 fix: remove faulty EC test
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#840 fix: only require the inspect-image task for FBC PLRs
  pkg/utils/build/task_results.go
Labels: lgtm, approved

#835 test: add more tests for RemoteSecret and Environments interaction
  pkg/utils/remotesecret/remote_secrets.go
  tests/remote-secret/README.md
  tests/remote-secret/environments.go
Labels: lgtm, approved

#844 feat: added sonar properties
  sonar-project.properties
Labels: lgtm, approved

#842 fix: fix labels
  tests/remote-secret/environments.go
  tests/remote-secret/kubeconfig-auth.go
  tests/remote-secret/service-account-auth.go
  tests/remote-secret/target-current-namespace.go
Labels: approved

#846 test: temporarily disabling failing EC test
  tests/build/build_templates.go
Labels: lgtm, approved

#847 fix: build-templates: get valid git revision
  tests/build/build_templates.go
Labels: lgtm, approved

#833 feat: add build source image tests
  pkg/utils/build/image.go
  pkg/utils/build/source_image.go
  pkg/utils/util.go
  tests/build/build_templates.go
Labels: lgtm, approved
