Repository konflux-ci/e2e-tests, pull requests merged in 2023-09, with the labels that each got.

#688 feat: [RHTAP-1321] Refactor tekton controller code
  pkg/framework/framework.go
  pkg/logs/logs.go
  pkg/utils/has/components.go
  pkg/utils/tekton/bundles.go
  pkg/utils/tekton/containers.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/cosign_results.go
  pkg/utils/tekton/enterprise_contract_policies.go
  pkg/utils/tekton/images.go
  pkg/utils/tekton/matchers.go
  pkg/utils/tekton/persistent_volume_claims.go
  pkg/utils/tekton/pipelineruns.go
  pkg/utils/tekton/pipelines.go
  pkg/utils/tekton/rekor_hosts.go
  pkg/utils/tekton/signing_secret.go
  pkg/utils/tekton/taskruns.go
  pkg/utils/tekton/tasks.go
  pkg/utils/tekton/tekton_chains_public_keys.go
  pkg/utils/tekton/verify_enterprise_contract.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/build/jvm-build.go
  tests/byoc/byoc.go
  tests/enterprise-contract/contract.go
  tests/integration-service/integration.go
  tests/o11y/o11y-pipelinerun.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/release/neg-missing-releaseplanadmission.go
  tests/release/neg-missing-releasestrategy.go
  tests/release/neg-missingreleaseplan.go
  tests/release/release.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#743 fix: move EC pipelines tests to build-templates
  tests/build/build_templates.go
  tests/build/chains.go
Labels: lgtm, approved

#744 chore: bump jvm-build-service and image-ctrl
  go.mod
  go.sum
  magefiles/utils_test.go
Labels: lgtm, approved

#740 fix: use skopeo from ClusterTasks
  pkg/utils/tekton/taskruns.go
  tests/spi/quay-imagepullsecret-usage.go
Labels: lgtm, approved

#734 docs: add README file to integration service
  tests/integration-service/README.md
Labels: lgtm, approved

#748 fix: fix spi test suite label
  magefiles/magefile.go
Labels: approved

#746 feat(load-test): add additional basic metrics
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/cluster_read_config.yaml
Labels: lgtm, approved

#750 fix: delete EC PR if it completes successfully
  tests/build/build_templates.go
Labels: lgtm, approved

#749 feat(HACBS-2550): update release pipeline versions
  pkg/constants/constants.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#752 test: RHTAPBUGS-556 added timeout flag to curl command
  tests/spi/access-control.go
Labels: lgtm, approved

#716 feat: Private image repo flow
  pkg/constants/constants.go
  pkg/utils/build/quay.go
  pkg/utils/has/components.go
  tests/build/build.go
Labels: lgtm, approved

#738 feat(RHTAP-1516): Split single 'resource...' metric to apps, cdqs and components
  cmd/loadTests.go
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/load-tests-example.json
Labels: lgtm, approved

#742 refactor: Explicitly set IGNORE_REKOR value
  pkg/utils/tekton/pipelineruns.go
  pkg/utils/tekton/verify_enterprise_contract.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#755 fix: Typo in JSON field name, alligning with the rest
  cmd/loadTests.go
  tests/load-tests/load-tests-example.json
Labels: lgtm, approved

#496 test: (STONEINTG-398) Add Happy Path coverage for namespace-backed envs
  pkg/utils/gitops/deploymenttargetclasses.go
  pkg/utils/gitops/environments.go
  pkg/utils/integration/integration_test_scenarios.go
  pkg/utils/integration/pipelineruns.go
  pkg/utils/integration/snapshots.go
  tests/README.md
  tests/integration-service/README.md
  tests/integration-service/integration.go
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#708 feat: update CODEOWNER
  .github/CODEOWNERS
Labels: lgtm, approved

#759 feat: add multi-component test using same repo
  tests/build/build.go
  tests/build/const.go
Labels: lgtm, approved

#758 fix: remove the test we already have coverage for
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#764 fix: Skip namespace-backed-environments
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#745 feat: [RHTAP-1496] Storing functions for test resources
  pkg/logs/logs.go
  pkg/logs/utils.go
  pkg/utils/common/pod.go
  pkg/utils/common/snapshot_environment_bindings.go
  pkg/utils/gitops/deploymenttargetclaims.go
  pkg/utils/gitops/deploymenttargetclasses.go
  pkg/utils/gitops/deploymenttargets.go
  pkg/utils/gitops/environments.go
  pkg/utils/gitops/gitopsdeployments.go
  pkg/utils/has/applications.go
  pkg/utils/has/componentdetectionqueries.go
  pkg/utils/has/components.go
  pkg/utils/integration/snapshots.go
  pkg/utils/tekton/pipelineruns.go
  tests/build/jvm-build.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#751 chore: remove cluster registration tests
  cmd/e2e_test.go
  docs/LabelsNaming.md
  pkg/framework/describe.go
  tests/README.md
  tests/cluster-registration/README.md
  tests/cluster-registration/clusters.go
Labels: lgtm, approved

#762 feat(load-test): Add start and end timestamps to max-concurrency JSON
  tests/load-tests/run-max-concurrency.sh
Labels: enhancement, lgtm, approved

#765 feat(RHTAP-1566): Add more metadata to our status data JSON
  tests/load-tests/cluster_read_config.yaml
Labels: lgtm, approved

#770 fix(RHTAPBUGS-769): Enable the namespace-backed-environments test again
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#774 skip multi-component language until: https://issues.redhat.com/browse/RHTAPBUGS-804 is fixed
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#775 fix: Remove unused vars
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#766 test: RHTAPBUGS-556 add eventually to curl request
  tests/spi/access-control.go
Labels: lgtm, approved

#703 feat: Enable existing tests working with Pac+ Github App
  README.md
  default.env
  magefiles/installation/install.go
  magefiles/magefile.go
  magefiles/sprayproxy.go
  pkg/apis/github/pull_request.go
  pkg/constants/constants.go
  pkg/utils/util.go
  tests/build/build.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#779 feat(HACBS-2526): update release pipelines to use tekton api v1
  pkg/constants/constants.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#763 feat(STONEINTG-398): this is a follow-up enhancement PR
  pkg/constants/constants.go
  pkg/utils/common/snapshot_environment_bindings.go
  pkg/utils/gitops/environments.go
  pkg/utils/integration/pipelineruns.go
  pkg/utils/integration/snapshots.go
  tests/integration-service/integration.go
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#777 fix(load-test): replace scenarioContent string with a key=value set in the output JSON
  tests/load-tests/cluster_read_config.yaml
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#769 feat: multi component in different namespace with same git url
  tests/build/build.go
Labels: lgtm, approved

#768 feat: RHTAPBUGS-540 archive artifacts when DeleteAllComponentsInASpecificNamespace fails.
  pkg/framework/utils.go
  pkg/logs/utils.go
  tests/byoc/byoc.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#652 feat: RHTAP-456 PoC of Upgrade tests
  Makefile
  cmd/e2e_test.go
  default.env
  go.mod
  go.sum
  magefiles/installation/install.go
  magefiles/magefile.go
  magefiles/utils.go
  pkg/apis/kubernetes/client.go
  pkg/framework/describe.go
  pkg/sandbox/sandbox.go
  pkg/utils/gitops/gitopsdeployments.go
  tests/upgrade/README.md
  tests/upgrade/cleanupWorkload.go
  tests/upgrade/create/createUsers.go
  tests/upgrade/createWorkload.go
  tests/upgrade/utils/const.go
  tests/upgrade/utils/util.go
  tests/upgrade/verify/verifyUsers.go
  tests/upgrade/verifyWorkload.go
Labels: lgtm, approved

#783 feat: test ec-redhat-no-hermetic pipeline
  tests/build/build_templates.go
Labels: approved

#778 fix: RHTAPBUGS-257 Add noTimeoutDefaultTransport from sandbox repository to
  pkg/apis/kubernetes/client.go
Labels: approved

#786 feat(load-test): Propagate ENABLE_PROGRESS_BARS env variable to --enable-progress-bars flag
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#789 test: skip get-file-content test
  tests/spi/get-file-content.go
Labels: lgtm, approved

#788 fix: log the error and retry the GetComponent when it fails during CheckForImageAnnotations
  pkg/utils/has/components.go
Labels: lgtm, approved

#790 feat: update strategies to use new API
  go.mod
  go.sum
  pkg/utils/release/strategies.go
Labels: lgtm, approved

#771 chore: Remove sync-hac-frontend-configs pipeline.
  pipelines/sync-hac-frontend-configs/README.md
  pipelines/sync-hac-frontend-configs/cronjob.yaml
  pipelines/sync-hac-frontend-configs/eventlistener.yaml
  pipelines/sync-hac-frontend-configs/pipeline.yaml
  pipelines/sync-hac-frontend-configs/tasks.yaml
  pipelines/sync-hac-frontend-configs/triggertemplate.yaml
Labels: approved

#787 chore: add siddardh-ra to root OWNERS file
  OWNERS
Labels: needs-ok-to-test, do-not-merge/invalid-owners-file

#795 fix: register PaC proxy server in nightly job
  magefiles/magefile.go
Labels: lgtm, approved
