Repository konflux-ci/e2e-tests, pull requests merged in 2023-02, with the labels that each got.

#323 test: STONE-438 change forked repos to original one in E2E suite
  tests/e2e-demos/config/default.yaml
Labels: lgtm, approved

#328 fix: increase timeout for waiting on build pipelinerun
  tests/build/build.go
Labels: lgtm, approved

#330 fix: remove bundle init from tekton ctrl init
  pkg/framework/framework.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/controller_test.go
  tests/build/chains.go
Labels: lgtm, approved

#331 fix: bump timeout for chains pipelinerun tests
  tests/build/chains.go
Labels: lgtm, approved

#334 feat: Remove oauth since in openshift ci will log with kubeadmin and we can obtain oc token
  magefiles/installation/install.go
  magefiles/installation/oauth.go
Labels: approved

#335 fix: Remove pipelines in specific namespaces if succeed correctly
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/release/release.go
Labels: approved

#266 test: E2e test default bundle
  cmd/e2e_test.go
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/utils/common/controller.go
  pkg/utils/release/controller.go
  pkg/utils/tekton/controller.go
  tests/build/jvm-build.go
  tests/release/const.go
  tests/release/e2e-test-default-bundle.go
  tests/release/release.go
Labels: lgtm, ok-to-test, approved

#337 fix: Adding OWNERS file to tests/release with users of release team
  tests/release/OWNERS
Labels: lgtm, approved

#336 test: adding label 'pipeline' to identify the tests that are used for Pipeline Service tests
  docs/LabelsNaming.md
  tests/build/build.go
  tests/build/chains.go
Labels: lgtm, approved

#342 fix: increase build and release timeouts to avoid quay.io incident of…
  go.mod
  go.sum
  tests/build/build.go
  tests/release/const.go
Labels: lgtm, approved

#341 fix: checking pipelines running in parallel
  tests/build/build.go
Labels: lgtm, approved

#333 fix: jvm-build: skip CR deletion on a failure, nicer error output
  pkg/utils/has/controller.go
  pkg/utils/util.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#338 fix: Add samples to e2e-demos
  cmd/e2e_test.go
  go.sum
  pkg/utils/has/controller.go
  tests/e2e-demos/config/default.yaml
  tests/e2e-demos/config/types.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
Labels: approved

#339 feat: Run e2e demos in application-service PRs
  magefiles/magefile.go
Labels: lgtm, approved

#345 feat: Add more samples to e2e-demos like private nodejs repos
  tests/e2e-demos/config/default.yaml
Labels: approved

#346 feat: Add python with devfile test scenario
  tests/e2e-demos/config/default.yaml
Labels: lgtm, approved

#347 fix: override default JBS cache resource requests
  go.sum
  pkg/utils/jvmbuildservice/controller.go
Labels: lgtm, approved

#348 feat: Retry pipeline in case if fail for some external reasons like quay connection is flaky
  tests/e2e-demos/e2e-demo.go
Labels: approved

#327 fix: keep the app and component CRs when integration test fail
  tests/integration-service/integration.go
Labels: lgtm, approved

#340 feat: EC use default EnterpriseContractPolicy
  pkg/utils/tekton/controller.go
  tests/build/chains.go
Labels: lgtm, approved

#320 fix: update hacbs pipeline validation
  tests/build/build.go
Labels: lgtm, approved

#351 fix: STONE-530 check nil pointer in "finds the snapshot and checks if it is marked as successful"
  pkg/utils/integration/controller.go
  pkg/utils/util.go
  tests/e2e-demos/e2e-demo.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#261 feat: test jvm-build svc: override tekton bundle
  go.mod
  go.sum
  magefiles/magefile.go
  magefiles/utils.go
  pkg/constants/constants.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#354 fix: Update rp_preproc path
  pkg/framework/custom_junit_reporter.go
Labels: lgtm, approved

#353 feat(HACBS-1669): add case for running release-service PR check
  magefiles/magefile.go
Labels: lgtm, approved

#357 fix: release-service CI config
  magefiles/magefile.go
Labels: lgtm, approved

#325 feat: Run e2e tests throw toolchain proxy
  cmd/loadTests.go
  go.mod
  go.sum
  magefiles/installation/install.go
  magefiles/magefile.go
  magefiles/utils.go
  pkg/apis/kubernetes/client.go
  pkg/constants/constants.go
  pkg/framework/framework.go
  pkg/sandbox/keycloak.go
  pkg/sandbox/sandbox.go
  pkg/utils/common/controller.go
  pkg/utils/gitops/controller.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  pkg/utils/jvmbuildservice/controller.go
  pkg/utils/release/controller.go
  pkg/utils/spi/controller.go
  pkg/utils/tekton/controller.go
  tests/build/build.go
  tests/build/chains.go
  tests/build/jvm-build.go
  tests/cluster-registration/clusters.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
  tests/release/e2e-test-default-bundle.go
  tests/release/release.go
Labels: do-not-merge/hold, approved

#359 fix: Fixes pipelinerun retrigger
  pkg/framework/framework.go
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved

#360 test: STONE-604 increase timeout and improve GetIntegrationTestScenarios to consider application
  pkg/utils/integration/controller.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#361 fix: move framework init into BeforeAll
  go.sum
  pkg/framework/framework.go
  tests/build/chains.go
  tests/cluster-registration/clusters.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
  tests/integration-service/integration.go
  tests/release/e2e-test-default-bundle.go
  tests/release/release.go
Labels: lgtm, approved

#363 fix: update e2e issue reporting section in README
  README.md
Labels: lgtm, approved

#358 feat: STONE-522: add branch and context dir test scenario
  pkg/utils/has/controller.go
  tests/build/jvm-build.go
  tests/e2e-demos/config/default.yaml
  tests/e2e-demos/config/types.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/has/devfile_private_source.go
  tests/has/devfile_source.go
Labels: lgtm, approved, jira/valid-reference

#362 feat: Add command to remove webhooks from magefiles
  Makefile
  magefiles/magefile.go
Labels: lgtm, approved

#344 feat: mvp-demo automation
  cmd/e2e_test.go
  cmd/loadTests.go
  pkg/framework/describe.go
  pkg/sandbox/sandbox.go
  pkg/utils/common/controller.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
  tests/build/build.go
  tests/build/jvm-build.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#365 fix: CI setup for PRs from upstream branch
  magefiles/magefile.go
  magefiles/utils.go
Labels: lgtm, approved

#355 feat: Add doc link to help contribuitors to see how the e2e artifacts are in openshift CI
  README.md
Labels: lgtm, approved

#326 test: RHDP-513 add pipelinerun logs
  go.sum
  pkg/utils/has/controller.go
  pkg/utils/tekton/pipelines.go
  tests/build/build.go
  tests/e2e-demos/e2e-demo.go
  tests/e2e-demos/multi-component.go
  tests/integration-service/integration.go
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#350 test: STONE-438 change forked repos to original one in has and loadTests
  cmd/loadTests.go
  tests/has/README.md
  tests/has/const.go
Labels: lgtm, approved

#316 fix: Add release e2e-test running the default catalog bundle with a d…
  cmd/e2e_test.go
  pkg/utils/gitops/controller.go
  tests/release/const.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/release.go
Labels: lgtm, approved
