Repository konflux-ci/e2e-tests, pull requests merged in 2023-11, with the labels that each got.

#845 docs: SVPI-658 enhance and updated spi and remote-secret docs
  pkg/utils/common/snapshot_environment_bindings.go
  pkg/utils/remotesecret/remote_secrets.go
  pkg/utils/spi/file_content_requests.go
  tests/remote-secret/README.md
  tests/spi/README.md
Labels: lgtm, approved

#784 docs: RHTAP-1068: chore: Add e2e guidelines
  README.md
  docs/Guidelines.md
  docs/Installation.md
  docs/InvestigatingCIFailures.md
Labels: lgtm, approved, jira/valid-reference

#854 fix: RHTAPBUGS-939: Skip oauth tests until RHTAPBUGS-939 is resolved
  tests/spi/oauth.go
Labels: lgtm, jira/valid-reference

#853 fix: Exclude test directory in sonar
  sonar-project.properties
Labels: lgtm, approved

#848 feat(RHTAP-1726): Fix-GitHub-action-against-Stage
  .github/workflows/loadtest.yaml
  tests/load-tests/ci-scripts/stage/collect-results.sh
Labels: lgtm, approved

#862 fix: Increase golangci lint timeout to 10min
  .github/workflows/PR.yaml
Labels: lgtm, approved

#855 feat: RHTAPBUGS-804: Remove QD checks from e2e tests. We are already grooming QD in RHTAP
  tests/build/build.go
  tests/rhtap-demo/config/scenarios.go
  tests/rhtap-demo/rhtap-demo.go
Labels: approved, jira/valid-reference

#865 chore: re-enable PaC tests
  magefiles/magefile.go
  tests/build/build.go
  tests/rhtap-demo/config/scenarios.go
Labels: lgtm, approved

#866 docs: RHTAP-1148: add link to RHTAP cluster pools documentation
  docs/OpenShiftCI.md
Labels: lgtm, jira/valid-reference

#851 feat: add test for prevent unnecessary pipelineruns feature
  pkg/apis/github/pull_request.go
  pkg/utils/has/components.go
  tests/build/build.go
  tests/build/const.go
Labels: lgtm, approved

#814 test: SVPI-574 and SVPI-652: Ensure existence of image pull remote secret and image pull secret when component is created
  cmd/loadTests.go
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/framework/framework.go
  pkg/utils/build/quay.go
  pkg/utils/build/task_results.go
  pkg/utils/has/componentdetectionqueries.go
  pkg/utils/has/components.go
  pkg/utils/imagecontroller/controller.go
  pkg/utils/imagecontroller/image_repository.go
  pkg/utils/jvmbuildservice/controller.go
  pkg/utils/loadtests/controller.go
  pkg/utils/remotesecret/remote_secrets.go
  tests/release/pipelines/e2e-test-default-with-deployment.go
  tests/release/pipelines/e2e-test-push-image-to-pyxis.go
  tests/release/release.go
  tests/remote-secret/component-annotation-image-pull-remote-secret.go
  tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
  tests/remote-secret/kubeconfig-auth.go
  tests/remote-secret/service-account-auth.go
  tests/remote-secret/target-current-namespace.go
  tests/remote-secret/utils.go
Labels: jira/valid-reference

#856 fix: RHTAPBUGS-939 reenable "SPITokenBinding should be in Injected phase"
  tests/spi/oauth.go
Labels: lgtm, approved

#860 fix: RHTAP-1840 OmitTimelinesForSpecStates Passed,Skipped and
  pkg/framework/custom_junit_reporter.go
Labels: approved

#861 refactor: Remove Polarion related code
  cmd/e2e_test.go
  docs/DeveloperGenerateTest.md
  go.mod
  magefiles/magefile.go
  pkg/framework/polarion_reporter.go
  templates/test_suite_cmd.tmpl
Labels: approved

#849 chore: add debug info for rhtap demo and release
  pkg/utils/release/releases.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#852 chore: Get rid of GitOpsRepo check from Load test
  cmd/loadTests.go
Labels: lgtm, approved

#869 fix: RHTAPBUGS-955 increase timeout when checking if pod is running
  tests/spi/quay-imagepullsecret-usage.go
Labels: lgtm, approved

#843 fix(RHTAPREL-658): move and fix e2e-test-default-with-deployment.go
  cmd/e2e_test.go
  tests/release/service/const.go
  tests/release/service/happy_path_with_deployment.go
Labels: lgtm, approved

#874 fix: Check pipelinerun count instead of deleting pipelineruns
  tests/build/build.go
Labels: lgtm, approved

#839 feat(RHTAP-1532): Track-integration-test-scenario-resource-creation-time
  cmd/loadTests.go
Labels: approved

#870 chore: update enterprise-contract-controller
  go.mod
  go.sum
  pkg/utils/contract/policy.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#878 feat: add spi login page support
  tests/spi/oauth.go
Labels: lgtm

#871 chore: update owners files, add owners_aliases
  OWNERS
  OWNERS_ALIASES
  tests/build/OWNERS
  tests/enterprise-contract/OWNERS
  tests/integration-service/OWNERS
  tests/release/OWNERS
Labels: lgtm, approved

#873 feat(RHTAPREL-659): produce a test for the fbc-release pipeline
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved

#875 test(STONEINTG-609): e2e automation for reporting integration test status
  docs/Installation.md
  pkg/utils/integration/integration_test_scenarios.go
  pkg/utils/integration/pipelineruns.go
  tests/integration-service/README.md
  tests/integration-service/const.go
  tests/integration-service/integration.go
  tests/integration-service/namespace-backed-environments.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved

#881 chore: cleanup private repos older than 7 days
  Makefile
  magefiles/magefile.go
  magefiles/utils.go
Labels: lgtm, approved

#883 chore: Change byoc suite name to byoc-suite and remove duplicated suite
  pkg/framework/describe.go
  tests/byoc/byoc.go
  tests/rhtap-demo/config/scenarios.go
Labels: approved

#884 docs: clarify the branch pairing mechanism
  docs/Installation.md
Labels: lgtm, approved

#885 test: RHTAPBUGS-978 skipping component deletion
  tests/build/build.go
  tests/byoc/byoc.go
  tests/integration-service/integration.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#886 fix: register sprayproxy for integration-service
  magefiles/magefile.go
Labels: approved

#882 feat: support v1-style BuildPipelineSelector pipelineRef
  pkg/utils/tekton/bundles.go
  pkg/utils/util.go
  tests/build/build.go
Labels: lgtm, approved

#887 chore: prepare pipelineRef syntax for Tekton v1
  pkg/utils/integration/pipelineruns.go
  pkg/utils/tekton/pipelineruns.go
  pkg/utils/util.go
  tests/build/build.go
  tests/build/jvm-build.go
Labels: lgtm, approved

#888 feat(STONEINTG-600): Add tests for build plr finalizers
  tests/integration-service/integration.go
Labels: lgtm, approved

#891 fix: RHTAPBUGS-943 - increase timeout of CreateComponentDetectionQueryWithTimeout
  pkg/clients/has/componentdetectionqueries.go
  tests/integration-service/const.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved

#893 fix: docs : remote secret test
  tests/remote-secret/README.md
Labels: lgtm, approved

#850 fix: add release service test suites
  cmd/e2e_test.go
  magefiles/magefile.go
  pkg/framework/describe.go
  tests/release/OWNERS
  tests/release/const.go
  tests/release/neg-missingreleaseplan.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/service/happy_path.go
  tests/release/service/happy_path_with_deployment.go
  tests/release/service/missing_release_plan_and_admission.go
  tests/release/service/release_plan_owner_ref.go
Labels: lgtm, approved

#897 feat(RHTAPREL-732): update magefile for release-service-catalog repo
  magefiles/magefile.go
Labels: lgtm, approved

#895 fix(STONEBUGS-123): fix JVM Build Service tests
  pkg/utils/tekton/bundle.go
  pkg/utils/tekton/pipeline_extraction_test.go
Labels: lgtm, approved

#900 fix: env vars setup for release-service-catalog
  magefiles/magefile.go
Labels: lgtm, approved

#901 fix: Disable build tests in infra-deployments until flakiness are fixed
  magefiles/magefile.go
  tests/build/build_templates.go
Labels: lgtm, approved

#906 feat: RHTAPBUGS-985: retry pipelineruns when hit TaskRunImagePullFailed reason in Pipelinerun statuses
  pkg/clients/has/components.go
Labels: lgtm, approved, jira/valid-reference

#908 fix(RHTAPBUGS-989): Expected Build PLR to contain finalizer added by integration-service
  tests/integration-service/const.go
  tests/integration-service/integration.go
  tests/integration-service/namespace-backed-environments.go
Labels: lgtm, approved

#903 feat: modify disabled and status fields
  pkg/framework/custom_junit_reporter.go
Labels: lgtm, approved

#909 fix: checkRun variable not being updated
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved

#907 fix(RHTAPBUGS-1012): update to v1 API
  magefiles/magefile.go
Labels: lgtm, approved

#905 fix(RHTAP-1913): Fix-high-error-rate-in-CI
  cmd/loadTests.go
  pkg/clients/has/components.go
Labels: lgtm, approved

#828 chore: do not rely on 'vendor' folder
  .github/workflows/PR.yaml
  Dockerfile
  Makefile
  docs/Installation.md
  tests/load-tests/ci-scripts/setup-cluster.sh
Labels: lgtm, approved

#902 fix: Disable dotnet samples. They are not supported in rhtap
  tests/rhtap-demo/config/scenarios.go
Labels: approved

#899 feat: periodic cleanup of registered (and no longer valid) servers on qe sprayproxy
  Makefile
  magefiles/magefile.go
  pkg/clients/sprayproxy/sprayproxy.go
  pkg/clients/sprayproxy/types.go
Labels: lgtm, approved

#917 fix: RHTAPBUGS-985: retry pipelineruns always when error occurs
  pkg/clients/has/components.go
Labels: lgtm, approved, jira/valid-reference

#914 fix: update the values in data struct to pass the ec verification
  tests/release/pipelines/push_to_external_registry.go
Labels: lgtm, approved

#921 fix: Revert "fix: RHTAPBUGS-985: retry pipelineruns always when error occurs"
  pkg/clients/has/components.go
  tests/rhtap-demo/rhtap-demo.go
Labels: approved, jira/valid-reference

#912 test: RHTAPBUGS-978 increase timeout of component deletion + logs
  pkg/clients/has/components.go
  pkg/utils/build/quay.go
  tests/build/build.go
  tests/build/const.go
  tests/byoc/byoc.go
  tests/integration-service/integration.go
  tests/remote-secret/environments.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved
