Repository konflux-ci/e2e-tests, pull requests merged in 2023-03, with the labels that each got.

#374 fix: EC: exclude CVE check
  go.sum
  tests/mvp-demo/mvp-demo.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
Labels: lgtm, approved

#368 docs: removed Polarion chapter and Jira link, added oc version comment, fixed typo
  README.md
Labels: lgtm, approved

#372 docs: removed Test naming chapter
  docs/LabelsNaming.md
Labels: lgtm, approved

#373 docs: Updated links, style unification, fixed typos
  docs/DeveloperGenerateTest.md
  docs/LoadTests.md
  docs/OpenShiftCI.md
Labels: lgtm, approved

#375 fix: cleanup repositories when using github org seperate from redhat-appstudio-qe
  magefiles/magefile.go
Labels: lgtm, ok-to-test, approved

#370 feat(HACBS-1592): add case for running integrtion-service PR check
  magefiles/magefile.go
Labels: lgtm, approved

#378 fix: update mvp-demo "untrusted" build template
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#379 fix: PR and TR status checks
  pkg/constants/constants.go
  pkg/utils/has/controller.go
  pkg/utils/integration/controller.go
  tests/build/build.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#383 docs: improve readme
  README.md
  tests/mvp-demo/README.md
Labels: lgtm, approved

#381 docs: Update PR template
  .github/pull_request_template.md
Labels: lgtm, approved

#382 feat: Add pipeline for syncing frontend-configs to public github.
  pipelines/sync-hac-frontend-configs/README.md
  pipelines/sync-hac-frontend-configs/cronjob.yaml
  pipelines/sync-hac-frontend-configs/eventlistener.yaml
  pipelines/sync-hac-frontend-configs/pipeline.yaml
  pipelines/sync-hac-frontend-configs/tasks.yaml
  pipelines/sync-hac-frontend-configs/triggertemplate.yaml
Labels: lgtm, approved

#380 fix: update information about multi components skip issue
  tests/e2e-demos/multi-component.go
Labels: approved

#367 test: build: validate using custom default branch
  tests/build/build.go
Labels: lgtm, approved

#389 docs: Mention docker token env variable in the readme for avoiding pull limits
  README.md
Labels: lgtm, approved

#390 fix: STONE-770 rp_preproc folder cleanup fix
  pkg/framework/custom_junit_reporter.go
Labels: lgtm, approved

#369 test: added e2e test that verifies if rebuild uses cached dependencies
  pkg/constants/constants.go
  pkg/utils/tekton/controller.go
  tests/build/jvm-build.go
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved

#392 feat: PLNSRVCE-1087 Test Tekton Result stored in the persistent storage
  go.sum
  pkg/utils/pipeline/results.go
  tests/build/build.go
Labels: lgtm, approved

#386 feat: add EC validation to build test
  pkg/framework/framework.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/pipelines.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/build/const.go
  tests/mvp-demo/mvp-demo.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
Labels: lgtm, approved

#385 docs: STONE-553 Add InvestigatingCIFailures.md
  README.md
  docs/InvestigatingCIFailures.md
Labels: lgtm, approved

#401 chore: update ic-catcher people list to remove gitops qe
  pipelines/interrupt_catcher/cm_people_list.yaml
Labels: lgtm, approved

#398 test(STONEO11Y-44): Add initial o11y tests to e2e
  cmd/e2e_test.go
  pkg/framework/describe.go
  pkg/framework/framework.go
  pkg/utils/common/controller.go
  pkg/utils/o11y/controller.go
  tests/o11y/o11y.go
Labels: lgtm, approved

#402 fix: runtime errors in jvm-build-service test
  tests/build/jvm-build.go
Labels: lgtm, approved

#406 fix: HACBS-2004 update refs new EC GitHub org
  README.md
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/utils/tekton/controller.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/mvp-demo/README.md
  tests/mvp-demo/mvp-demo.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/release.go
Labels: lgtm, approved

#405 fix: Changes related to component delete check
  pkg/apis/github/git.go
  tests/build/build.go
Labels: lgtm, approved

#415 docs: Add Copyright owner in license file
  LICENSE
Labels: lgtm, approved

#416 fix: fixed tag for release pipeline
  pkg/constants/constants.go
  tests/mvp-demo/mvp-demo.go
  tests/release/const.go
  tests/release/e2e-test-default-bundle.go
Labels: lgtm, approved
