Repository konflux-ci/e2e-tests, pull requests merged in 2023-05, with the labels that each got.

#479 fix(RHTAPBUGS-197): enable pyxis tests again
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#478 test: SVPI-408 - skopeo copy task test
  pkg/utils/tekton/controller.go
  tests/mvp-demo/README.md
  tests/spi/README.md
  tests/spi/const.go
  tests/spi/get-file-content.go
  tests/spi/quay-imagepullsecret-usage.go
  tests/spi/token-upload-rest-endpoint.go
  tests/spi/var.go
Labels: lgtm, approved

#491 refactor: use fixed versions for release pipeline bundles
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, approved

#486 fix: tekton v0.45.0 compatibility, enable integration-service tests
  go.mod
  go.sum
  pkg/utils/build/task_results.go
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/pipelines.go
  pkg/utils/util.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/chains.go
  tests/build/jvm-build.go
  tests/enterprise-contract/contract.go
  tests/integration-service/integration.go
  tests/release/e2e-test-push-image-to-pyxis.go
Labels: lgtm, do-not-merge/hold, approved

#495 fix: allow for override of test-image used by mvp-demo
  pkg/constants/constants.go
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#490 fix: add timeout when checking spi upload secret is removed
  tests/spi/token-upload-k8s.go
Labels: lgtm, approved

#467 feat: add CleanupQuayTags
  Makefile
  go.mod
  go.sum
  magefiles/magefile.go
  magefiles/utils.go
  magefiles/utils_test.go
Labels: lgtm, approved

#493 chore(HACBS-1032): changes AutoReleaseLabel import package to metadata
  go.mod
  go.sum
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
Labels: lgtm, approved

#505 fix: RHTAPBUGS-49: use sandbox spaces to get usernamespace instead of hardcoding
  go.mod
  go.sum
  pkg/apis/kubernetes/client.go
  pkg/framework/framework.go
  pkg/sandbox/sandbox.go
  tests/enterprise-contract/contract.go
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved, jira/valid-reference

#503 test: SVPI-473 collect SPI ResourceQuota metrics (temporary)
  pkg/utils/common/resource_quota.go
  tests/spi/get-file-content.go
  tests/spi/link-secret-sa.go
  tests/spi/quay-imagepullsecret-usage.go
  tests/spi/token-upload-k8s.go
  tests/spi/token-upload-rest-endpoint.go
Labels: lgtm, approved

#508 feat: STONEBLD-1241: Switch service account to appstudio-pipeline
  pkg/constants/constants.go
  pkg/framework/framework.go
  pkg/utils/common/namespace.go
  pkg/utils/o11y/controller.go
  tests/build/build.go
  tests/o11y/const.go
  tests/release/const.go
  tests/release/e2e-test-default-bundle.go
  tests/release/e2e-test-default-with-deployment.go
  tests/release/e2e-test-push-image-to-pyxis.go
  tests/release/release.go
Labels: lgtm, approved, jira/valid-reference

#511 fix: using specific data and policy for Release policy "out of date" test case
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#514 fix(STONEINTG-414): add digest to sample image
  tests/integration-service/integration.go
Labels: lgtm, approved

#522 fix: log gitops endpoint err
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved

#526 fix(RHTAPBUGS-276): use default image repo instead of internal registry
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/pipelines.go
  tests/build/chains.go
Labels: lgtm, approved

#524 fix: sample app can be built successfully should use DEFAULT_QUAY_ORG
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#528 fix: bug in e2e-test default bundle
  pkg/constants/constants.go
  tests/release/e2e-test-default-bundle.go
Labels: lgtm, approved

#530 fix: remove reference to the old SA
  tests/build/build.go
Labels: lgtm, approved

#492 feat(RHTAP-668): Introduce CI scripts for load test
  cmd/loadTests.go
  pkg/utils/has/controller.go
  pkg/utils/util.go
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/load-test.sh
  tests/load-tests/ci-scripts/setup-cluster.sh
  tests/load-tests/run.sh
Labels: lgtm, approved

#471 feat: RHTAP-862: byoc automated tests
  cmd/e2e_test.go
  go.mod
  go.sum
  magefiles/magefile.go
  pkg/apis/kubernetes/client.go
  pkg/apis/vcluster/types.go
  pkg/apis/vcluster/vcluster.go
  pkg/utils/common/cluster.go
  pkg/utils/gitops/controller.go
  pkg/utils/has/controller.go
  pkg/utils/release/controller.go
  pkg/utils/util.go
  tests/byoc/README.md
  tests/byoc/byoc.go
  tests/byoc/types.go
  tests/e2e-demos/config/types.go
  tests/e2e-demos/e2e-demo.go
Labels: lgtm, approved, jira/valid-reference

#523 fix: RHTAP-912: fail Eventually ginkgo clauses on terminal failure states; all ginkgo 'Should' clauses should have debug info including keys
  tests/mvp-demo/mvp-demo.go
  tests/utils.go
Labels: lgtm, approved, jira/valid-reference

#510 fix: refactored taskrun results validation
  pkg/utils/build/task_results.go
  tests/build/build_templates.go
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved

#529 fix: chains: check attestation and signature
  go.mod
  go.sum
  pkg/utils/tekton/controller.go
  pkg/utils/tekton/controller_test.go
  tests/build/chains.go
Labels: lgtm, approved

#501 feat: ec validate can take mulitiple images as input
  pkg/utils/tekton/pipelines.go
  tests/enterprise-contract/const.go
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#497 feat(load-test): Include more detailed information about errors occurred during test execution
  cmd/loadTests.go
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/load-test.sh
  tests/load-tests/clear.sh
  tests/load-tests/load-tests-example.json
  tests/load-tests/run.sh
Labels: lgtm, approved

#538 fix: RHTAPBUGS-343: Check host until DEVHAS-367 is ready and implemented
  pkg/utils/util.go
  tests/byoc/byoc.go
Labels: lgtm, approved, jira/valid-reference

#543 chore: added collaborators to root OWNERS file
  OWNERS
Labels: lgtm, approved

#541 fix: ensure chains and EC suites run in unique ns
  pkg/constants/constants.go
  tests/build/chains.go
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#549 fix: Add byoc to infra-deployments running tests
  go.mod
  go.sum
  magefiles/magefile.go
  pkg/utils/common/cluster.go
  tests/build/build_templates.go
  tests/build/chains.go
Labels: lgtm, approved

#551 fix: framework init, log more info during fw init
  pkg/constants/constants.go
  pkg/framework/framework.go
  pkg/sandbox/keycloak.go
  pkg/sandbox/sandbox.go
Labels: lgtm, approved

#545 fix(load-test): Fix collecting results
  cmd/loadTests.go
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/clear.sh
  tests/load-tests/load-tests-example.json
Labels: lgtm, approved

#527 feat(STONEINTG-403): add test for creating DTC with nonexisting avaiable DTCLS
  pkg/utils/integration/controller.go
  tests/integration-service/integration.go
Labels: lgtm, approved

#531 fix: RHTAP-915: mvp-demo debug update
  pkg/utils/util.go
  tests/mvp-demo/mvp-demo.go
  tests/utils.go
Labels: lgtm, approved, jira/valid-reference

#546 feat(HACBS-2127): add author to ReleasePlan labels
  pkg/utils/integration/controller.go
  pkg/utils/release/controller.go
Labels: lgtm, approved

#552 test: spi tests - get resource after resource creation
  pkg/utils/tekton/controller.go
  tests/spi/get-file-content.go
  tests/spi/link-secret-sa.go
  tests/spi/quay-imagepullsecret-usage.go
  tests/spi/token-upload-k8s.go
  tests/spi/token-upload-rest-endpoint.go
Labels: approved

#553 fix: RHTAPBUGS-356: Skip mvp release tests until RHTAPBUGS-356 is solved
  tests/mvp-demo/mvp-demo.go
Labels: lgtm, approved, jira/valid-reference
