Repository konflux-ci/e2e-tests, pull requests merged in 2024-03, with the labels that each got.

#1061 fix: Retry removing finalizer from pipelineruns
  tests/build/build_templates.go
Labels: lgtm, approved

#1058 fix(kfluxbugs-1128): fix rhtap-demo falkiness
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved

#1048 feat: add team specific template generation
  docs/DeveloperGenerateTest.md
  magefiles/magefile.go
  pkg/testspecs/astginkgos.go
  pkg/testspecs/const.go
  pkg/testspecs/ginkgosspec.go
  pkg/testspecs/ginkgosspec_test.go
  pkg/testspecs/templates.go
  pkg/testspecs/textspec.go
  pkg/testspecs/types.go
  templates/default/recommended.tmpl
  templates/default/testOutline
  templates/specs.tmpl
Labels: lgtm, approved

#1065 fix: The clair-scan task is not required for FBC pipelines
  pkg/utils/build/task_results.go
Labels: lgtm, approved

#1063 fix: show-summary task check
  tests/build/build_templates.go
Labels: lgtm, approved

#1068 feat: add allowedPackages for the fbc test
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved

#1067 fix: extend the Chains attestation timeout
  pkg/constants/constants.go
  tests/build/build_templates.go
  tests/build/jvm-build.go
  tests/enterprise-contract/contract.go
Labels: lgtm, approved

#1070 chore: print fbc application name
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved

#1072 fix: argocd CVE
  go.mod
  go.sum
Labels: lgtm, approved

#1064 fix(KONFLUX-2311): Fix PVC function in load test
  cmd/loadTests.go
Labels: lgtm, approved

#1071 feat: Add aws dynamic instance allocation tests
  pkg/clients/common/pod.go
  tests/build/multi-platform.go
Labels: lgtm, approved

#1083 ci: add estimate PR review time workflow
  .github/workflows/estimate-review.yaml
Labels: lgtm, approved

#1086 fix: do not delete hosts with invalid certs
  magefiles/magefile.go
Labels: lgtm, approved, < 1 min

#1080 ci: refine OWNERS files
  OWNERS
  pkg/clients/imagecontroller/OWNERS
  pkg/clients/integration/OWNERS
  pkg/clients/jvmbuildservice/OWNERS
  pkg/clients/release/OWNERS
Labels: lgtm, approved

#1090 fix: ocp upgrade: available/conditional updates
  magefiles/upgrade/upgrade.go
Labels: lgtm, approved, < 1 min

#1089 chore: add token refreshing and refine the fbc test cases
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved, 1-5 min

#1087 chore: add myself to rhtap-qe alias.
  OWNERS_ALIASES
Labels: lgtm, ok-to-test, approved, < 1 min

#1082 perf: drop the push-sbom-to-pyxis task
  tests/release/pipelines/rh_push_to_external_registry.go
Labels: lgtm, approved

#1091 fix(STONEBLD-2265): increase chains timeout since chains controller is overwhelmed
  pkg/constants/constants.go
Labels: lgtm, approved, < 1 min

#1078 feat: Added tests for multi-platform dynamic IBM P&Z
  Makefile
  go.mod
  go.sum
  magefiles/magefile.go
  tests/build/multi-platform.go
Labels: lgtm, approved, 15-30 min

#1074 fix(load-test): fix max concurrency collect results script, add tekton result watcher metrics
  tests/load-tests/ci-scripts/max-concurrency/cluster_read_config.yaml
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/run-max-concurrency.sh
Labels: lgtm, approved

#1085 feat(KONFLUX-926): Track git commit status
  tests/load-tests/cluster_read_config.yaml
Labels: lgtm, approved, < 1 min

#1069 feat(RHTAPREL-849): add e2e test for release_to_github
  pkg/clients/github/repositories.go
  tests/release/const.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/release_to_github.go
  tests/release/releaseLib.go
Labels: lgtm, approved, 5-10 min

#1098 fix(KFLUXBUGS-1147): update checkRun name for build pipelineRun
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved, < 1 min

#1102 chore: skip flakey IBM PPC test
  tests/build/multi-platform.go
Labels: lgtm, approved, < 1 min

#1073 feat(STONEBLD-1832): add tests to check parent sources are included
  go.mod
  pkg/clients/tekton/taskruns.go
  pkg/utils/build/image.go
  pkg/utils/build/source_image.go
  tests/build/build_templates.go
  tests/build/source_build.go
Labels: lgtm, approved
