Repository konflux-ci/e2e-tests, pull requests merged in 2024-11, with the labels that each got.

#1445 chore: skip multicomponent test with same git url
  tests/build/build.go
Labels: lgtm, approved, < 1 min

#1421 refactor: use generic client in gitlab build tests
  go.mod
  go.sum
  pkg/clients/git/git.go
  pkg/clients/git/github.go
  pkg/clients/git/gitlab.go
  tests/build/build.go
Labels: lgtm, approved, 5-10 min

#1450 chore: enable rh_push_to_redhat_io
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, < 1 min

#1453 fix: bump golanci-lint action
  .github/workflows/PR.yaml
Labels: lgtm, < 1 min

#1455 chore: increase timeout and skip removing branches
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1446 chore: Revert "skip multicomponent test with same git url"
  tests/build/build.go
Labels: lgtm, approved, < 1 min

#1447 fix: isPaired need to be set
  magefiles/rulesengine/repos/release_service_catalog.go
Labels: lgtm, approved, < 1 min

#1459 feat(KONFLUX-4319): Capture Application & Component JSONs after load test
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/stage/collect-results.sh
  tests/load-tests/pkg/journey/handle_collections.go
Labels: lgtm, approved, 1-5 min

#1461 feat(STONEINTG-1009): e2e tests for group snapshot
  pkg/clients/has/components.go
  pkg/clients/integration/pipelineruns.go
  tests/integration-service/const.go
  tests/integration-service/group-snapshots-tests.go
  tests/integration-service/integration.go
Labels: lgtm, approved, 10-15 min

#1463 chore: skipping the tkn-bundle test
  tests/build/tkn-bundle.go
Labels: lgtm, approved, < 1 min

#1436 feat(RELEASE-1199): fbc release e2e should contain the test for staged
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved, 1-5 min

#1467 fix: wrap the pipeline run signed check inside eventually
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, < 1 min

#1464 fix: add docker-build-multi-platform-oci-ta pipeline test
  magefiles/rulesengine/repos/e2e_repo.go
  pkg/utils/build/source_image.go
  tests/build/build_templates_scenarios.go
Labels: lgtm, approved, 1-5 min

#1469 fix: add docker.io creds to tekton-logging ns
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: approved, < 1 min
