Repository konflux-ci/e2e-tests, pull requests merged in 2024-10, with the labels that each got.

#1411 feat(KONFKUX-4009): Add mage engine rules for image-controller repo
  magefiles/magefile.go
  magefiles/rulesengine/engine/engine.go
  magefiles/rulesengine/repos/image_controller.go
Labels: lgtm, approved, 1-5 min

#1413 feat: add no-color flag to e2e tests
  magefiles/magefile.go
Labels: lgtm, approved, < 1 min

#1414 feat(KONFKUX-4006): Add mage engine rules for build-service repo
  magefiles/magefile.go
  magefiles/rulesengine/engine/engine.go
  magefiles/rulesengine/repos/build_service.go
Labels: lgtm, approved, 1-5 min

#1399 fix(KFLUXBUGS-1487): Duplicated build PLRs in GitLab e2e test
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, approved, < 1 min

#1415 fix: use finalizer lock in EC build-definitions
  tests/build/build_templates.go
Labels: lgtm, < 1 min

#1416 feat: Lower number of iterations when creating user
  pkg/sandbox/sandbox.go
Labels: lgtm, approved, < 1 min

#1420 feat(RELEASE-1205): create engine rule for release catalog
  magefiles/magefile.go
  magefiles/rulesengine/engine/engine.go
  magefiles/rulesengine/repos/common.go
  magefiles/rulesengine/repos/release_service_catalog.go
Labels: lgtm, approved, 1-5 min

#1428 fix: add --no-color to rules
  magefiles/rulesengine/repos/common.go
Labels: lgtm, approved, < 1 min

#1382 feat(KONFLUX-4272): Cleanup as non-PaC builds are gone, also make the templating option bit more generic
  tests/load-tests/ci-scripts/utility_scripts/runs-to-csv.sh
  tests/load-tests/loadtest.go
  tests/load-tests/pkg/journey/handle_component.go
  tests/load-tests/pkg/journey/handle_repo_templating.go
  tests/load-tests/pkg/journey/journey.go
  tests/load-tests/pkg/options/options.go
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: lgtm, approved, 1-5 min

#1427 fix: link pull secret to console-sa for minio
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: lgtm, approved, < 1 min

#1417 feat: verify REPORTS result from clair-scan Task
  pkg/clients/oras/client.go
  pkg/utils/build/task_results.go
Labels: lgtm, approved, 1-5 min

#1423 fix(KONFLUX-4965): add prometheus metrics to max-concurrency collector
  tests/load-tests/ci-scripts/max-concurrency/cluster_read_config.yaml
Labels: lgtm, approved, 1-5 min

#1430 feat(KONFLUX-4272): Update latest PaC config in run-stage-max-concurrency.sh
  tests/load-tests/run-stage-max-concurrency.sh
Labels: lgtm, approved, < 1 min

#1418 feat: create generic git client interface
  pkg/clients/common/controller.go
  pkg/clients/git/git.go
  pkg/clients/git/github.go
  pkg/clients/git/gitlab.go
  pkg/utils/build/git.go
Labels: lgtm, approved, 5-10 min

#1422 fix(KONFLUX-4925): Fix Github Action Setup for perf load-test
  .github/workflows/loadtest.yaml
Labels: lgtm, approved, 1-5 min

#1419 feat: add tests for nudging gitlab repos
  tests/build/build.go
Labels: lgtm, approved, 1-5 min

#1431 feat: update createReleasePlan function
  go.mod
  go.sum
  pkg/clients/release/plans.go
  tests/integration-service/integration.go
  tests/konflux-demo/konflux-demo.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
  tests/release/service/happy_path.go
  tests/release/service/release_plan_and_admission_matched.go
  tests/release/service/release_plan_owner_ref.go
  tests/release/service/tenant_pipelines.go
Labels: lgtm, approved, 1-5 min

#1433 fix: update release multiarch data fields
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/rh_advisories.go
Labels: lgtm, approved, < 1 min

#1429 feat(RELEASE-1201): get pipelineRun logs from staging cluster
  pkg/clients/release/releases.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
  tests/release/releaseLib.go
Labels: lgtm, approved, 5-10 min

#1402 fix(KFLUXBUGS-1614): fbc pipeline should stop passing binaryimage to iib
  pkg/constants/constants.go
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved, < 1 min

#1437 fix: typo in restoreRelease
  pkg/clients/release/releases.go
Labels: lgtm, approved, < 1 min

#1440 fix: release advisory pipelines should use RHBA
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/rh_advisories.go
Labels: lgtm, approved, < 1 min

#1441 chore: cleanup in build tests
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min
