Repository konflux-ci/e2e-tests, pull requests merged in 2024-04, with the labels that each got.

#1093 fix: Fix Untar to create parent dirs when necessary
  pkg/utils/util.go
Labels: lgtm, approved, < 1 min

#1104 chore: KFLUXBUGS-1179 skip ibmz tests
  tests/build/multi-platform.go
Labels: lgtm, approved, < 1 min

#1108 chore: disable tekton-results pipeline logs check
  tests/build/build_templates.go
Labels: approved, quarantine, < 1 min

#1109 fix: fixed tag of buildah-remote task for MP test
  magefiles/magefile.go
Labels: approved, < 1 min

#1106 docs: update GH token required scopes
  docs/Installation.md
Labels: approved, < 1 min

#1110 fix: add option to skip scheduling on master nodes
  default.env
  magefiles/installation/install.go
  pkg/constants/constants.go
  tests/load-tests/ci-scripts/setup-cluster.sh
Labels: lgtm, approved, < 1 min

#984 feat(RHTAP-1742): Add metric to track average task pod duration by Tekton measurements
  tests/load-tests/ci-scripts/stage/cluster_read_config.yaml
Labels: lgtm, approved, 1-5 min

#1113 feat: Add script to convert bunch of downloaded benchmark JSONs into CSV
  tests/load-tests/ci-scripts/utility_scripts/runs-to-csv.sh
Labels: lgtm, approved, 1-5 min

#1112 feat: Add OCP cluster version
  tests/load-tests/cluster_read_config.yaml
Labels: lgtm, approved, < 1 min

#1117 fix: address issues with tests
  pkg/utils/tekton/pipelineruns.go
  tests/build/multi-platform.go
Labels: lgtm, approved, < 1 min

#1121 fix: renew framework every 3 minutes
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved, < 1 min

#1124 fix: follow-up on the devfile schema version incompatibility issue
  tests/build/const.go
Labels: lgtm, approved, < 1 min

#1122 fix: re-trigger non-pac build
  pkg/clients/has/components.go
  pkg/constants/constants.go
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1126 test: Stop testing deprecated ec pipelines
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1116 feat(KONFLUX-2602): Make it possible to create a component with 'build.appstudio.openshift.io/request: configure-pac'
  cmd/loadTests.go
Labels: lgtm, approved, < 1 min

#1100 feat(RHTAPREL-806): update operator toolkit refrence
  go.mod
  go.sum
  tests/integration-service/integration.go
Labels: lgtm, approved, < 1 min

#1125 feat(STONEINTG-697): remove SEB case created for successful snapshot
  tests/integration-service/README.md
  tests/integration-service/integration.go
Labels: lgtm, approved, < 1 min

#1135 feat(STONEINTG-837): update org of integration-examples
  cmd/loadTests.go
  tests/integration-service/const.go
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
  tests/rhtap-demo/config/scenarios.go
Labels: lgtm, approved, < 1 min

#1132 fix(RHTAPREL-842): preGA and hotfix can't be set both
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved, < 1 min

#1107 feat: add tests related to secret lookup
  tests/build/build.go
  tests/build/const.go
Labels: lgtm, approved, 1-5 min

#1136 fix: update EC policy inclusion
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1130 feat(KONFLUX-2456): remove SEB and Env checks from rhtap-demo and remote
  tests/remote-secret/component-annotation-image-pull-remote-secret.go
  tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, < 1 min

#1137 feat: match new extra-src filename form
  pkg/utils/build/source_image.go
Labels: lgtm, approved, < 1 min

#1131 feat(RELEASE-500): update release service catalog reference to konflux ci
  tests/release/const.go
  tests/release/pipelines/README.md
Labels: lgtm, approved, < 1 min

#1129 fix: ginkgo spec generation if path contains dash
  pkg/testspecs/ginkgosspec.go
  pkg/testspecs/templates.go
Labels: lgtm, approved, < 1 min

#1097 feat(RHTAPREL-869): add e2e tests for create-advisory pipeline
  pkg/clients/release/plans.go
  tests/integration-service/integration.go
  tests/release/const.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/service/happy_path.go
  tests/release/service/release_plan_and_admission_matched.go
  tests/release/service/release_plan_owner_ref.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 10-15 min

#1138 fix(KONFLUX-2744): Add PaC secrets
  tests/load-tests/ci-scripts/setup-cluster.sh
  tests/load-tests/cluster_read_config.yaml
Labels: lgtm, approved, < 1 min

#1142 fix(STONEINTG-697): e2e-tests will stop watching for successful deployments
  tests/byoc/byoc.go
  tests/rhtap-demo/README.md
  tests/rhtap-demo/config/scenarios.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, < 1 min

#1143 refactor(KONFLUX-2391): remove byoc test suite
  cmd/e2e_test.go
  docs/Installation.md
  magefiles/magefile.go
  pkg/clients/common/cluster.go
  pkg/clients/kubernetes/client.go
  pkg/clients/vcluster/types.go
  pkg/clients/vcluster/vcluster.go
  pkg/framework/describe.go
  pkg/utils/util.go
  tests/README.md
  tests/byoc/README.md
  tests/byoc/byoc.go
  tests/byoc/types.go
Labels: lgtm, approved, 5-10 min
