Repository konflux-ci/e2e-tests, pull requests merged in 2024-09, with the labels that each got.

#1322 fix(KONFLUX-3986): fix CSV header generator
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
Labels: lgtm, ok-to-test, approved, < 1 min

#1365 fix: fix pipelines timeout
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
  tests/release/releaseLib.go
Labels: lgtm, approved, 5-10 min

#1288 feat: add GitLab coverage for PaC component build tests
  default.env
  pkg/clients/gitlab/git.go
  pkg/clients/has/components.go
  pkg/constants/constants.go
  pkg/utils/build/git.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/const.go
  tests/build/jvm-build.go
  tests/build/multi-platform.go
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, ok-to-test, approved, 15-30 min

#1363 chore: Add new task to create OCI artifacts and improve e2e runner script
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
  integration-tests/scripts/konflux-e2e-runner.sh
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, do-not-merge/hold, approved, 5-10 min

#1331 fix(KFLUXBUGS-1416): FBC fragment released to the wrong OCP version
  pkg/constants/constants.go
Labels: lgtm, approved, < 1 min

#1371 chore: Update konflux CI pipeline to use new naming for storage artifacts
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: lgtm, approved, < 1 min

#1372 chore: Revert fork name from pipelines
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, < 1 min

#1257 feat: check pushed Dockerfile
  go.mod
  pkg/clients/oras/client.go
  tests/build/build_templates.go
  tests/build/multi-platform.go
Labels: lgtm, approved, 1-5 min

#1381 fix: Pin gosec and upgrade upload-sarif action
  .github/workflows/PR.yaml
Labels: lgtm, approved, < 1 min

#1377 chore: change tenant pipeline test case to use a simpler pipeline
  tests/release/service/tenant_pipelines.go
Labels: lgtm, approved, < 1 min

#1370 fix(RELEASE-1149): e2e keeps checking pipelinerun even if it failed
  tests/release/pipelines/fbc_release.go
  tests/release/releaseLib.go
Labels: lgtm, approved, < 1 min

#1347 feat(KONFLUX-3187): infra-deployments test selection fix
  magefiles/rulesengine/repos/infra_deployments.go
Labels: lgtm, approved, < 1 min

#1383 fix: delete pipelinerun finalizer issue
  pkg/clients/tekton/pipelineruns.go
Labels: lgtm, approved, < 1 min

#1361 fix: use custom bundle in e2e-tests
  magefiles/magefile.go
  pkg/utils/build/custom_bundle.go
  tests/build/build.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration.go
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, 5-10 min

#1390 chore: add tnevrlka to build OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved, < 1 min

#1389 fix: skip the dockerfile check for hermatic and fbc scenarios
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
Labels: lgtm, approved, < 1 min

#1391 fix: run release-pipelines tests if modified in PR
  magefiles/rulesengine/repos/e2e_repo.go
Labels: lgtm, approved, < 1 min

#1392 chore: add rh-rahulshetty user to perf-team alias
  OWNERS_ALIASES
Labels: lgtm, ok-to-test, approved, < 1 min

#1375 fix: If all the journeys failed, do not compute avg KPI time
  tests/load-tests/evaluate.py
  tests/load-tests/run-max-concurrency.sh
Labels: lgtm, approved, < 1 min

#1384 feat: Test different Pipeline variants
  pkg/clients/tekton/bundles.go
  pkg/constants/constants.go
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
  tests/build/const.go
  tests/build/source_build.go
Labels: lgtm, approved, 10-15 min

#1386 feat(STONEINTG-660): renaming clair scan result
  pkg/utils/build/task_results.go
Labels: lgtm, approved, < 1 min

#1385 feat: Script to list and remove GitHub repos in org
  tests/load-tests/ci-scripts/utility_scripts/github-org-cleanup-repos.py
Labels: lgtm, approved, 1-5 min

#1387 fix(KONFLUX-997): Adds a check to handle loadtest.go errors
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run.sh
Labels: lgtm, ok-to-test, approved, < 1 min

#1393 feat: test multi-platform pipeline
  tests/build/build_templates_scenarios.go
Labels: lgtm, approved, < 1 min

#1398 chore: add zxiong user to perf-team alias
  OWNERS_ALIASES
Labels: lgtm, ok-to-test, approved, < 1 min

#1206 chore: migrate build-definitions redhat-appstudio images
  tests/release/const.go
Labels: lgtm, approved, < 1 min

#1396 fix: skip creating multiple component for symlink test
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
Labels: lgtm, approved, < 1 min

#1394 feat(RELEASE-1172): add a mage engine rule for release-service
  magefiles/magefile.go
  magefiles/rulesengine/engine/engine.go
  magefiles/rulesengine/repos/release_service.go
Labels: lgtm, approved, 1-5 min

#1403 feat(KONFLUX-4178): Add script to run max-concurrency tests on staging cluster
  tests/load-tests/.gitignore
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/ci-scripts/max-concurrency/load-test.sh
  tests/load-tests/run-stage-max-concurrency.sh
Labels: lgtm, approved, 5-10 min

#1401 feat(RELEASE-1147): update repository to registry.redhat.io in rpa
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
Labels: lgtm, approved, < 1 min

#1405 feat(EC-885): step-report to step-report-json
  tests/build/build_templates.go
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1406 fix: add docker secret to tekton-results and minio
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: lgtm, < 1 min

#1408 fix: increase konflux-e2e tests run time limitation
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: lgtm, approved, < 1 min

#1404 feat: enable dockerfile check for hermetic builds
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1409 fix: add more checking in getfailedtask
  pkg/utils/tekton/pipelineruns.go
Labels: lgtm, approved, < 1 min

#1395 chore(stoneintg-942): update readme with new test info
  tests/integration-service/README.md
Labels: lgtm, approved, < 1 min

#1410 fix: re-trigger pipeline run failure issue
  pkg/clients/has/components.go
Labels: lgtm, approved, < 1 min
