Repository konflux-ci/e2e-tests, pull requests merged in 2024-05, with the labels that each got.

#1092 feat(KONFLUX-2084): Make it possible to create more components in one app
  cmd/loadTests.go
  pkg/clients/integration/integration_test_scenarios.go
Labels: lgtm, approved, 15-30 min

#1127 feat(EC-456): Create tests for tkn-bundle task
  pkg/clients/common/pod.go
  pkg/clients/common/secret.go
  pkg/clients/github/pull_request.go
  pkg/clients/tekton/persistent_volume_claims.go
  pkg/clients/tekton/taskruns.go
  pkg/constants/constants.go
  pkg/framework/describe.go
  pkg/utils/build/git.go
  tests/build/build_templates.go
  tests/build/tkn-bundle.go
Labels: lgtm, approved, 15-30 min

#1148 chore: add perf-test OWNERS files
  OWNERS_ALIASES
  cmd/OWNERS
  tests/load-tests/OWNERS
Labels: lgtm, approved, < 1 min

#1146 refactor: Remove CreateIntegrationTestScenarioV2() and extend signature of original function
  cmd/loadTests.go
  pkg/clients/integration/integration_test_scenarios.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, < 1 min

#1139 fix: PaC: get correct commit SHA after PLR rerun
  pkg/clients/has/components.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/jvm-build.go
  tests/build/multi-platform.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/service/happy_path.go
  tests/remote-secret/component-annotation-image-pull-remote-secret.go
  tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 5-10 min

#1149 refactor(KFLUXBUGS-1115): rh_push_to_external_registry refactor
  pkg/clients/release/sbom.go
  tests/release/pipelines/rh_push_to_external_registry.go
Labels: lgtm, approved, < 1 min

#1150 chore: add approvers for release dir in pkg
  pkg/clients/release/OWNERS
Labels: lgtm, approved, < 1 min

#1145 chore(DEVHAS-648): Remove GitOps repository related test code
  magefiles/magefile.go
  pkg/clients/has/applications.go
  pkg/utils/gitops/gitops_repository.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/jvm-build.go
  tests/build/multi-platform.go
  tests/integration-service/integration.go
  tests/remote-secret/component-annotation-image-pull-remote-secret.go
  tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 1-5 min

#1157 fix(EC-624): tkn-bundle bug fixes
  pkg/clients/common/pod.go
  tests/build/tkn-bundle.go
Labels: lgtm, approved, < 1 min

#1156 fix: Use golden-container latest images in enterprise contract tests
  pkg/utils/tekton/pipelineruns.go
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1160 fix: skip tkn-bundle task test temporarily
  tests/build/tkn-bundle.go
Labels: lgtm, approved, < 1 min

#1161 chore(STONEINTG-836): integration-service to konflux-ci org
  cmd/loadTests.go
  go.mod
  go.sum
  pkg/clients/integration/integration_test_scenarios.go
  pkg/clients/integration/pipelineruns.go
  pkg/clients/integration/snapshots.go
  pkg/clients/kubernetes/client.go
  tests/README.md
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 1-5 min

#1153 feat(STONEINTG-869): e2e test of gitlab integration reporting
  go.mod
  pkg/clients/common/controller.go
  pkg/clients/gitlab/client.go
  pkg/clients/gitlab/git.go
  pkg/constants/constants.go
  tests/integration-service/const.go
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, approved, 10-15 min

#1154 feat: check source images built on top of Konflux images
  .gitignore
  pkg/utils/build/image.go
  pkg/utils/build/source_image.go
  tests/build/build_templates.go
  tests/build/source_build.go
Labels: lgtm, approved, 5-10 min

#1164 chore: prepare for go v1.21
  Dockerfile
  docs/Installation.md
  go.mod
  go.sum
Labels: lgtm, approved, < 1 min

#1158 chore(DEVHAS-662): Remove Environment API from e2e-tests
  pkg/clients/common/snapshot_environment_bindings.go
  pkg/clients/gitops/environments.go
  pkg/clients/integration/integration_test_scenarios.go
  pkg/framework/utils.go
Labels: lgtm, approved, 1-5 min

#1152 feat(RELEASE_425): add e2e tests for rh_push_to_redhat_io pipeline
  tests/release/const.go
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, 5-10 min

#1159 feat(STONEINTG-870): add e2e for reporting failing integration test to GL
  tests/integration-service/const.go
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, approved, 1-5 min

#1166 fix: release pyxis tests properly fetch imageIDs
  pkg/clients/release/sbom.go
Labels: lgtm, approved, < 1 min

#1169 feat: stop checking deprecated source image tag
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1165 fix: cleanup PaC webhooks after test's finished
  magefiles/magefile.go
  pkg/constants/constants.go
  pkg/framework/framework.go
  tests/build/build.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved, 1-5 min

#1168 fix: add renew framework for build pipelineRun
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, 1-5 min

#1167 feat: add test coverage for redhat policy check
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1170 chore: Move Image Controller to konflux-ci GitHub org
  go.mod
  go.sum
  magefiles/magefile.go
  magefiles/utils.go
  magefiles/utils_test.go
  pkg/clients/imagecontroller/image_repository.go
  pkg/clients/kubernetes/client.go
  pkg/clients/remotesecret/remote_secrets.go
  pkg/utils/build/quay.go
  tests/build/build.go
  tests/release/quay.go
  tests/remote-secret/component-annotation-image-pull-remote-secret.go
  tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
  tests/remote-secret/utils.go
Labels: lgtm, approved, 1-5 min

#1172 fix: always rebase e2e-tests and infra-deployments
  magefiles/installation/install.go
  magefiles/utils.go
  tests/load-tests/ci-scripts/setup-cluster.sh
Labels: lgtm, approved, < 1 min

#1173 feat(RELEASE-906): add WaitForReleasePipelineToBeFinished function
  pkg/clients/release/releases.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/service/happy_path.go
Labels: lgtm, approved, 5-10 min

#1162 feat: add a make target to build-bundle with custom source build image
  Makefile
  magefiles/magefile.go
  pkg/constants/constants.go
  tests/build/build_templates.go
  tests/build/const.go
Labels: lgtm, approved, 1-5 min

#1179 chore: update build-definitions references to new org
  .tekton/update-build-definitions.yaml
Labels: lgtm, approved, < 1 min

#1180 fix: upgrade job
  magefiles/installation/install.go
  magefiles/utils.go
Labels: lgtm, approved, < 1 min

#1182 fix: access token expired during pipelineRun
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, 1-5 min

#1183 fix: remove waiting the Argo CD role/rb to be set
  pkg/clients/common/namespace.go
  pkg/clients/common/rbac.go
Labels: lgtm, approved, < 1 min

#1184 fix: use loop or function with loop to get CRs
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, 1-5 min

#1171 feat(STONEINTG-881): update intg GCL test for GCL logic change
  tests/integration-service/integration.go
Labels: lgtm, approved, < 1 min

#1185 chore: fix GH app installation ID for PR creation
  .tekton/update-build-definitions.yaml
Labels: lgtm, approved, < 1 min

#1177 fix(KONFLUX-2465): Refresh framework before access token expires on Stage
  pkg/framework/framework.go
Labels: lgtm, approved, < 1 min

#1187 feat(STONEINTG-881): enable GCL test
  tests/integration-service/integration.go
Labels: lgtm, approved, < 1 min

#1188 fix: invalid memory or nil pointer issue
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, 1-5 min

#1190 chore: qe-tools moved to konflux-ci org
  .github/workflows/estimate-review.yaml
Labels: lgtm, approved, < 1 min

#1189 fix: remote names
  magefiles/installation/install.go
  magefiles/magefile.go
Labels: lgtm, approved, < 1 min

#1195 fix: ignore source correlated check in EC tests
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min
