Repository konflux-ci/e2e-tests, pull requests merged in 2024-08, with the labels that each got.

#1281 fix(KFLUXBUGS-1297): failure for an already successful snapshot
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, < 1 min

#1299 fix: Increase limits again
  .tekton/konflux-e2e-tests-push.yaml
  default.env
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
  integration-tests/tasks/konflux-e2e-tests-task.yaml
  magefiles/magefile.go
Labels: lgtm, approved, 1-5 min

#1302 fix: Remove fla bull shits code
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: lgtm, approved, < 1 min

#1300 fix: adapt the change of spliting aws-secret into 2 secrets
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: needs-ok-to-test, < 1 min

#1307 chore: skip jvm-build-service related tests
  tests/build/jvm-build.go
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, < 1 min

#1306 chore: Ussually a task have by default 1h timeout. Increase timeout to 2h
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: lgtm, approved, < 1 min

#1099 chore: bump golangci-lint version
  .github/workflows/PR.yaml
Labels: lgtm, approved, < 1 min

#1308 chore: Use external secret from vault in e2e tests
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, < 1 min

#1316 chore: Add docker.io credentials to avoid pull limits
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, < 1 min

#1309 fix: remove simple build dependency from build and integration tests
  pkg/clients/has/components.go
  pkg/clients/tekton/pipelineruns.go
  pkg/utils/build/git.go
  pkg/utils/build/task_results.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
  tests/build/const.go
  tests/build/jvm-build.go
  tests/build/multi-platform.go
  tests/build/source_build.go
  tests/integration-service/const.go
  tests/integration-service/integration-with-env.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/konflux-demo/config/scenarios.go
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, 30-60 min

#1318 chore: workaround to pull otel images using docker io creds
  integration-tests/tasks/konflux-e2e-tests-task.yaml
  magefiles/magefile.go
  magefiles/rulesengine/repos/e2e_repo.go
Labels: approved, 1-5 min

#1319 fix: Fix e2e repo rule engine
  magefiles/rulesengine/repos/e2e_repo.go
Labels: approved, < 1 min

#1314 chore: Upgrade testing infrastructure secrets
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: do-not-merge/hold, < 1 min

#1321 chore: Workaround to allow to test konflux e2e task in e2e-repo pull requests
  integration-tests/scripts/konflux-e2e-runner.sh
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, 5-10 min

#1320 refactor: remove PAC_GITLAB_* env vars
  integration-tests/scripts/konflux-e2e-runner.sh
  magefiles/magefile.go
  pkg/clients/common/controller.go
  pkg/clients/gitlab/git.go
  pkg/clients/has/components.go
  pkg/clients/has/controller.go
  pkg/constants/constants.go
  tests/build/const.go
  tests/integration-service/const.go
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, ok-to-test, approved, 1-5 min

#1325 chore(STONEINTG-1028): revert deletion of Integration service e2e-tests
  docs/Installation.md
  tests/integration-service/const.go
  tests/integration-service/integration-with-env.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved, 15-30 min

#1328 chore: Modify e2e pipeline and task to allow to execute e2e tasks in Konflux components
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, 10-15 min

#1329 fix(STONEINTG-1028): correct the name of GL repo
  magefiles/rulesengine/repos/e2e_repo.go
  tests/integration-service/const.go
Labels: lgtm, approved, < 1 min

#1336 chore: update GH repo name to prevent auto-cleanup
  docs/Installation.md
  tests/integration-service/const.go
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, approved, < 1 min

#1334 chore: pending release happy-path temporarily
  tests/release/service/happy_path.go
Labels: lgtm, approved, < 1 min

#1327 chore: don't run builds when readmes or other irrelevant changes to code are modified
  .tekton/konflux-e2e-tests-pull-request.yaml
  .tekton/konflux-e2e-tests-push.yaml
  magefiles/rulesengine/repos/e2e_repo.go
Labels: approved, < 1 min

#1339 fix: golangci-lint issues
  magefiles/magefile.go
  pkg/clients/common/secret.go
  pkg/clients/has/components.go
  pkg/clients/integration/pipelineruns.go
  pkg/clients/release/releases.go
  pkg/sandbox/keycloak.go
  pkg/sandbox/sandbox.go
  pkg/utils/build/quay.go
  pkg/utils/build/source_image.go
  pkg/utils/loadtests/controller.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_rh_advisories.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
Labels: lgtm, 1-5 min

#1335 feat(RELEASE-1104): triggering release pipelines by snapshots
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
  tests/release/pipelines/tenant_pipelines.go
  tests/release/releaseLib.go
  tests/release/service/happy_path.go
Labels: lgtm, approved, 15-30 min

#1338 feat(STONEINTG-975): e2e tests for IntegrationTestScenarios contexts
  pkg/clients/integration/integration_test_scenarios.go
  pkg/clients/integration/pipelineruns.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration-with-env.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/konflux-demo/konflux-demo.go
  tests/load-tests/pkg/journey/handle_integration_test_scenarios.go
Labels: 1-5 min

#1326 chore: update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved, < 1 min

#1341 chore: Do not run pipelinerun when pull_request is in draft mode
  .tekton/konflux-e2e-tests-pull-request.yaml
Labels: lgtm, approved, < 1 min

#1343 fix: do not overwrite the global public key
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/service/happy_path.go
Labels: lgtm, approved, < 1 min

#1342 fix: konflux-ci: ignore load tests changes
  .tekton/konflux-e2e-tests-pull-request.yaml
Labels: lgtm, approved, < 1 min

#1332 fix: unregister PaC server after konflux-ci test run
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: lgtm, approved, < 1 min

#1323 feat(KONFLUX-3187): adding test selection logic for repo infra-deploy…
  go.mod
  go.sum
  magefiles/magefile.go
  magefiles/rulesengine/engine/engine.go
  magefiles/rulesengine/repos/infra_deployments.go
  magefiles/rulesengine/types.go
  magefiles/utils.go
Labels: lgtm, approved, 5-10 min

#1333 fix(KFLUXBUGS-1533): GitLab build PLR fails on retrigger due to empty projectID
  pkg/clients/has/components.go
  pkg/constants/constants.go
Labels: lgtm, approved, < 1 min

#1340 chore: remove dependency from build to release const.go
  magefiles/rulesengine/repos/e2e_repo.go
  pkg/constants/constants.go
  tests/build/build.go
  tests/release/service/happy_path.go
Labels: lgtm, approved, < 1 min

#1351 feat: Add a test repo with dockerfile using from scratch
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
  tests/build/jvm-build.go
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, < 1 min

#1353 fix: Use new location for golden-container image
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1350 feat(STONEINTG-931): remove sbom-json-check
  .tekton/konflux-e2e-tests-pull-request.yaml
  .tekton/konflux-e2e-tests-push.yaml
  go.mod
  pkg/utils/build/task_results.go
Labels: lgtm, approved, 1-5 min

#1352 chore: Save e2e outputs to oci artifacts
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: lgtm, approved, < 1 min

#1354 chore: pending release-to-gitHub test
  tests/release/pipelines/release_to_github.go
Labels: lgtm, approved, < 1 min

#1356 fix: remove duplicate test run command
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: approved, < 1 min

#1348 feat: integration-service repo CI rule
  magefiles/magefile.go
  magefiles/rulesengine/engine/engine.go
  magefiles/rulesengine/repos/common.go
  magefiles/rulesengine/repos/e2e_repo.go
  magefiles/rulesengine/repos/integration_service.go
  magefiles/rulesengine/types.go
Labels: lgtm, approved, 1-5 min

#1357 chore: Fix exit code in the scripts
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: lgtm, approved, < 1 min

#1358 chore: add owner file in release dir
  tests/release/OWNERS
Labels: lgtm, approved, < 1 min

#1345 feat(RELEASE-1121): migrate the images re-used to hacbs-release-tests
  tests/release/const.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
  tests/release/service/happy_path.go
Labels: lgtm, approved, 1-5 min

#1360 chore: several changes for release pipelines
  pkg/clients/release/releases.go
  pkg/utils/tekton/pipelineruns.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
Labels: approved, < 1 min

#1359 chore: Mount konflux test infra volume to access oci storage
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, < 1 min
