Repository konflux-ci/e2e-tests, pull requests merged in 2024-07, with the labels that each got.

#1198 feat(RELEASE-190): add e2e tests for tenant pipeline
  go.mod
  go.sum
  pkg/clients/release/plans.go
  tests/integration-service/integration.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/tenant_pipelines.go
  tests/release/service/happy_path.go
  tests/release/service/release_plan_and_admission_matched.go
  tests/release/service/release_plan_owner_ref.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 5-10 min

#1228 chore(KONFLUX-2504): remove spi and remote-secret tests, utils, and references
  cmd/e2e_test.go
  docs/Guidelines.md
  go.mod
  go.sum
  magefiles/installation/install.go
  magefiles/magefile.go
  magefiles/upgrade/upgrade.go
  pkg/clients/common/resource_quota.go
  pkg/clients/kubernetes/client.go
  pkg/clients/remotesecret/controller.go
  pkg/clients/remotesecret/remote_secrets.go
  pkg/clients/spi/access_checks.go
  pkg/clients/spi/access_token_bindings.go
  pkg/clients/spi/access_tokens.go
  pkg/clients/spi/controller.go
  pkg/clients/spi/file_content_requests.go
  pkg/clients/spi/uploads.go
  pkg/constants/constants.go
  pkg/framework/describe.go
  pkg/framework/framework.go
  pkg/framework/utils.go
  pkg/testspecs/templates.go
  scripts/spi-e2e-setup.sh
  tests/README.md
  tests/build/build.go
  tests/build/const.go
  tests/build/jvm-build.go
  tests/remote-secret/README.md
  tests/remote-secret/kubeconfig-auth.go
  tests/remote-secret/service-account-auth.go
  tests/remote-secret/target-current-namespace.go
  tests/remote-secret/utils.go
  tests/rhtap-demo/README.md
  tests/rhtap-demo/rhtap-demo.go
  tests/spi/README.md
  tests/spi/access-control.go
  tests/spi/const.go
  tests/spi/get-file-content-rs.go
  tests/spi/get-file-content.go
  tests/spi/link-secret-sa.go
  tests/spi/oauth.go
  tests/spi/quay-imagepullsecret-usage.go
  tests/spi/token-upload-k8s.go
  tests/spi/token-upload-rest-endpoint.go
  tests/spi/var.go
Labels: lgtm, approved, 15-30 min

#1245 chore: validate offboarding is done successfully with github token
  tests/build/build.go
Labels: lgtm, approved, < 1 min

#1248 chore: Adapt all pipelineruns to Konflux
  .tekton/konflux-e2e-tests-pull-request.yaml
  .tekton/konflux-e2e-tests-push.yaml
  .tekton/pull-request.yaml
  .tekton/push.yaml
  .tekton/update-build-definitions.yaml
  .tekton/update-build-tasks-dockerfiles.yaml
Labels: approved, 5-10 min

#1244 feat: Add validation for floating tags functionality
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
  tests/build/const.go
Labels: lgtm, approved, 1-5 min

#1249 fix: Fix deprecated task bundles
  .tekton/konflux-e2e-tests-push.yaml
Labels: lgtm, approved, < 1 min

#1250 fix: Fix tasks-dockerfiles update script
  .tekton/konflux-e2e-tests-push.yaml
Labels: lgtm, approved, < 1 min

#1236 feat(STONEINTG-979): add gitlab and environment tests in README
  tests/integration-service/README.md
Labels: lgtm, approved, < 1 min

#1240 feat(RELEASE-106): add e2e tests for rhtap-service-push pipeline
  tests/release/pipelines/rhtap_service_push.go
Labels: lgtm, approved, 5-10 min

#1259 chore: update ec readme
  tests/enterprise-contract/README.md
Labels: lgtm, approved, < 1 min

#1253 fix: adapt e2e tests to backward compatibility reconciler in Image Controller
  pkg/clients/has/components.go
  pkg/clients/imagecontroller/image_repository.go
  pkg/utils/build/quay.go
  tests/build/build.go
Labels: lgtm, approved, 1-5 min

#1258 feat(RELEASE-927): add multi arch test with rh-advisories pipeline
  tests/release/pipelines/multiarch_rh_advisories.go
Labels: lgtm, approved, 5-10 min

#1237 fix: Do not fail collection if this fails
  tests/load-tests/ci-scripts/stage/collect-results.sh
Labels: lgtm, approved, < 1 min

#1238 feat: For local runs, I use this field to distinguish runs
  tests/load-tests/ci-scripts/utility_scripts/runs-to-csv.sh
Labels: lgtm, approved, < 1 min

#1242 feat: Playwright script to regenerate offline tokens
  tests/load-tests/ci-scripts/utility_scripts/playwright-update-tokens.py
Labels: lgtm, approved, 1-5 min

#1263 fix(KFLUXBUGS-1310): use GitLab API when retriggering GitLab-based Build PLRs
  pkg/clients/gitlab/git.go
  pkg/clients/has/components.go
  pkg/clients/has/controller.go
Labels: lgtm, approved, 1-5 min

#1261 chore(stoneintg-930): update ITS v1beta2 in e2e
  go.mod
  go.sum
  pkg/clients/integration/integration_test_scenarios.go
  pkg/clients/integration/pipelineruns.go
  pkg/clients/kubernetes/client.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration-with-env.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/load-tests/pkg/journey/handle_integration_test_scenarios.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 1-5 min

#1265 fix: stop checking BASE_IMAGES_DIGESTS
  pkg/utils/build/source_image.go
  tests/build/source_build.go
Labels: lgtm, approved, < 1 min

#1269 fix: Looks like missing kind is a known bug
  tests/load-tests/pkg/journey/handle_collections.go
Labels: lgtm, approved, < 1 min

#1270 fix: stop creating build-secret when github app installed
  tests/build/build.go
Labels: lgtm, approved, < 1 min

#1254 feat: KONFLUX-3383 Add initial test selection framework
  cmd/e2e_test.go
  magefiles/magefile.go
  magefiles/rulesengine/engine/engine.go
  magefiles/rulesengine/readme.md
  magefiles/rulesengine/repos/common.go
  magefiles/rulesengine/repos/e2e_repo.go
  magefiles/rulesengine/repos/infra_deployments.go
  magefiles/rulesengine/repos/rule_demo.go
  magefiles/rulesengine/types.go
  magefiles/utils.go
Labels: lgtm, approved, 30-60 min

#1272 chore: add rules for release service catalog testing
  magefiles/magefile.go
  magefiles/rulesengine/repos/e2e_repo.go
  magefiles/rulesengine/types.go
Labels: lgtm, approved, 1-5 min

#1274 chore: update rules for release service catalog testing
  magefiles/magefile.go
  magefiles/rulesengine/engine/engine.go
  magefiles/rulesengine/repos/e2e_repo.go
  magefiles/rulesengine/repos/release_service_catalog.go
Labels: lgtm, approved, 1-5 min

#1275 fix: remove DeepEqual check
  magefiles/magefile.go
Labels: lgtm, approved, < 1 min

#1277 fix: don't print SBOM
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1260 feat(KONFLUX-3150): add component-specific labels to e2e-tests
  cmd/e2e_test.go
  default.env
  docs/Installation.md
  magefiles/magefile.go
  magefiles/rulesengine/readme.md
  magefiles/rulesengine/repos/infra_deployments.go
  magefiles/utils_test.go
  pkg/framework/describe.go
  pkg/framework/failure_report_test.go
  tests/README.md
  tests/build/build.go
  tests/build/jvm-build.go
  tests/build/tkn-bundle.go
  tests/enterprise-contract/contract.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/konflux-demo/README.md
  tests/konflux-demo/config/scenarios.go
  tests/konflux-demo/config/types.go
  tests/konflux-demo/konflux-demo.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/service/happy_path.go
  tests/release/service/missing_release_plan_and_admission.go
  tests/release/service/release_plan_and_admission_matched.go
  tests/release/service/release_plan_owner_ref.go
Labels: lgtm, approved, 1-5 min

#1271 feat: Put additional collected data to dedicated directory
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/stage/collect-results.sh
Labels: lgtm, approved, < 1 min

#1266 refactor(KONFLUX-3773): Fork repositories sequentially
  tests/load-tests/loadtest.go
  tests/load-tests/pkg/journey/handle_repo_templating.go
  tests/load-tests/pkg/journey/journey.go
Labels: lgtm, approved, < 1 min

#1280 fix: Add oras to konflux container to push artifacts
  Dockerfile
Labels: approved, < 1 min

#1279 feat(KONFLUX-3857): Stop Mintmaker creating 'chore: ...' update PRs that provoke 'on-pull-request' builds that might interfere with testing
  pkg/constants/constants.go
  tests/load-tests/loadtest.go
  tests/load-tests/pkg/journey/handle_component.go
  tests/load-tests/pkg/options/options.go
Labels: lgtm, approved, < 1 min

#1286 fix: increase ticker time for fbc pipeline
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved, < 1 min

#1222 fix: Print PipelineRun status
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1289 chore: skip init check in build pipelineRun
  tests/release/pipelines/rhtap_service_push.go
  tests/release/releaseLib.go
Labels: lgtm, approved, < 1 min

#1234 fix: KONFLUX-3551: Onboard Konflux e2e utilities in Konflux CI
  Dockerfile
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
  integration-tests/tasks/konflux-e2e-tests-task.yaml
  magefiles/magefile.go
  magefiles/types.go
Labels: lgtm, approved, 30-60 min

#1293 fix: Add removed params during migration to a new konflux workspace
  .tekton/konflux-e2e-tests-push.yaml
Labels: approved, < 1 min

#1282 fix: fix and improve test selection rules for e2e-tests repo
  magefiles/rulesengine/repos/common.go
  magefiles/rulesengine/repos/e2e_repo.go
  magefiles/rulesengine/types.go
Labels: lgtm, approved, 5-10 min

#1297 fix: Fix oras username and oras password
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, < 1 min

#1298 fix: Fix task exit_code, improve memory and fix deprecated-img
  .tekton/konflux-e2e-tests-pull-request.yaml
  .tekton/konflux-e2e-tests-push.yaml
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, < 1 min

#1264 chore(KONFLUX-3654): Refactor konflux-demo test suite and remove simple build coverage
  pkg/constants/constants.go
  pkg/utils/build/secret.go
  tests/konflux-demo/README.md
  tests/konflux-demo/config/scenarios.go
  tests/konflux-demo/config/types.go
  tests/konflux-demo/const.go
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, 30-60 min
