Repository konflux-ci/e2e-tests, pull requests merged in 2024-06, with the labels that each got.

#1197 fix: expect EC check not to fail
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1199 fix: check for either appstudio- or konflux- prefix for the pacPurgeBranchName
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, < 1 min

#1201 fix: secret-lookup tests changed to use organization where github app is not installed
  pkg/clients/github/git.go
  tests/build/build.go
  tests/build/const.go
Labels: lgtm, approved, 1-5 min

#1204 fix: fix ec policy rules
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/service/happy_path.go
Labels: lgtm, approved, < 1 min

#1192 fix: remove devfile dependency and add pipeline annotation in component
  cmd/loadTests.go
  pkg/clients/has/componentdetectionqueries.go
  pkg/clients/has/components.go
  pkg/constants/constants.go
  pkg/framework/utils.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/jvm-build.go
  tests/build/multi-platform.go
  tests/integration-service/const.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/releaseLib.go
  tests/release/service/happy_path.go
  tests/remote-secret/component-annotation-image-pull-remote-secret.go
  tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
  tests/rhtap-demo/config/scenarios.go
  tests/rhtap-demo/config/types.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 15-30 min

#1202 test(STONEBLD-2377): Remove tests for build -push and -pull remote secret
  tests/remote-secret/component-annotation-image-pull-remote-secret.go
  tests/remote-secret/image-repository-cr-image-pull-remote-secret.go
Labels: lgtm, approved, 1-5 min

#1203 fix: checking CheckRuns conclusion in GitHub
  pkg/clients/github/pull_request.go
  pkg/constants/constants.go
  tests/build/build.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved, 1-5 min

#1174 refactor: Update application-api references
  cmd/loadTests.go
  go.mod
  go.sum
  magefiles/utils_test.go
  pkg/clients/common/test_status.go
  pkg/clients/gitops/deploymenttargetclaims.go
  pkg/clients/gitops/deploymenttargetclasses.go
  pkg/clients/gitops/deploymenttargets.go
  pkg/clients/has/applications.go
  pkg/clients/has/components.go
  pkg/clients/integration/pipelineruns.go
  pkg/clients/integration/snapshots.go
  pkg/clients/kubernetes/client.go
  pkg/framework/utils.go
  pkg/utils/tekton/verify_enterprise_contract.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/jvm-build.go
  tests/build/multi-platform.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/releaseLib.go
  tests/release/service/happy_path.go
  tests/release/service/missing_release_plan_and_admission.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 5-10 min

#1207 chore(DEVHAS-651): Remove test code for deprecated controllers
  pkg/clients/has/applications.go
  pkg/clients/has/components.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, < 1 min

#1209 fix: some error in rh_push_to_redhat_io
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, < 1 min

#1210 feat: allow pairing 3 repositories
  magefiles/magefile.go
Labels: lgtm, approved, < 1 min

#1208 fix: use fbc-builder pipeline instead of docker-build
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/releaseLib.go
  tests/release/service/happy_path.go
Labels: lgtm, approved, < 1 min

#1191 feat(stoneintg-937): add cleanup of webhooks in afterall
  pkg/clients/gitlab/git.go
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, approved, < 1 min

#1213 fix: undefined compName in release test
  tests/release/pipelines/rh_push_to_external_registry.go
Labels: lgtm, approved, < 1 min

#1214 fix: update PLR SHA if PLR was retriggered
  tests/build/build.go
Labels: lgtm, approved, < 1 min

#1215 fix: var fw was replaced by devFw wrongly
  tests/release/pipelines/push_to_external_registry.go
Labels: lgtm, approved, < 1 min

#1212 chore: Remove BuildPipelineSelector
  go.mod
  magefiles/magefile.go
  pkg/clients/has/components.go
  pkg/clients/tekton/bundles.go
  pkg/constants/constants.go
  pkg/utils/tekton/bundle.go
  pkg/utils/tekton/pipeline_extraction_test.go
  tests/build/build_templates.go
  tests/build/multi-platform.go
Labels: lgtm, approved, 5-10 min

#1217 fix: clean up the release created by the test
  tests/release/pipelines/release_to_github.go
Labels: lgtm, approved, < 1 min

#1176 refactor(RELEASE-920): release pipeline tests use new tag format
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, < 1 min

#1220 chore: konflux and k8s packages' versions bump
  go.mod
  go.sum
  pkg/clients/kubernetes/client.go
  pkg/clients/release/plans.go
  pkg/clients/release/releases.go
  pkg/clients/release/sbom.go
  pkg/clients/tekton/persistent_volume_claims.go
  pkg/utils/tekton/bundle.go
  pkg/utils/tekton/persistent_volume_claims.go
  tests/README.md
  tests/build/build.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/service/README.md
  tests/release/service/happy_path.go
  tests/release/service/missing_release_plan_and_admission.go
  tests/release/service/release_plan_and_admission_matched.go
  tests/release/service/release_plan_owner_ref.go
  tests/rhtap-demo/rhtap-demo.go
Labels: lgtm, approved, 5-10 min

#1218 fix: changes to build-defintions CI e2e-tests after build-pipeline-selector removal
  pkg/constants/constants.go
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
  tests/build/const.go
Labels: lgtm, approved, 1-5 min

#1223 fix: unregister PaC from sprayproxy separately
  Makefile
  magefiles/magefile.go
Labels: lgtm, approved, < 1 min

#1224 fix: move image repo to konflux-ci org
  .github/workflows/PR.yaml
  .github/workflows/build.yaml
  .tekton/pull-request.yaml
  .tekton/push.yaml
Labels: lgtm, approved, 1-5 min

#1163 refactor: Refactor load test
  .github/workflows/loadtest.yaml
  cmd/OWNERS
  cmd/loadTests.go
  docs/LoadTests.md
  pkg/clients/github/git.go
  pkg/clients/github/repositories.go
  pkg/clients/has/components.go
  pkg/clients/tekton/pipelineruns.go
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/load-test.sh
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/ci-scripts/max-concurrency/load-test.sh
  tests/load-tests/ci-scripts/merge-json.sh
  tests/load-tests/ci-scripts/offline-token-regeneration/convert_users_list_to_json_v2.sh
  tests/load-tests/ci-scripts/offline-token-regeneration/json_split_and_encode_v2.sh
  tests/load-tests/ci-scripts/stage/collect-results.sh
  tests/load-tests/ci-scripts/user-prefix.sh
  tests/load-tests/ci-scripts/utility_scripts/count-multiarch-taskruns.py
  tests/load-tests/ci-scripts/utility_scripts/runs-to-csv.sh
  tests/load-tests/ci-scripts/utility_scripts/show-pipelineruns.py
  tests/load-tests/ci-scripts/utils.sh
  tests/load-tests/clear.sh
  tests/load-tests/evaluate.py
  tests/load-tests/loadtest.go
  tests/load-tests/pkg/journey/handle_applications.go
  tests/load-tests/pkg/journey/handle_collections.go
  tests/load-tests/pkg/journey/handle_component.go
  tests/load-tests/pkg/journey/handle_integration_test_scenarios.go
  tests/load-tests/pkg/journey/handle_persistent_volume_claim.go
  tests/load-tests/pkg/journey/handle_pipeline.go
  tests/load-tests/pkg/journey/handle_purge.go
  tests/load-tests/pkg/journey/handle_repo_templating.go
  tests/load-tests/pkg/journey/handle_test_run.go
  tests/load-tests/pkg/journey/handle_users.go
  tests/load-tests/pkg/journey/journey.go
  tests/load-tests/pkg/loadtestutils/userutils.go
  tests/load-tests/pkg/logging/logging.go
  tests/load-tests/pkg/logging/time_and_log.go
  tests/load-tests/pkg/options/options.go
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: lgtm, ok-to-test, approved, > 60 min

#1226 fix(max-concurrency): fix result collection of max-concurrency test for new iteration directories
  tests/load-tests/ci-scripts/max-concurrency/collect-results.sh
  tests/load-tests/run-max-concurrency.sh
Labels: lgtm, needs-ok-to-test, approved, 1-5 min

#1225 chore: disable release-policy test
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1227 fix: nil pointer reference to PipelineRun object
  pkg/clients/has/components.go
Labels: lgtm, approved, < 1 min

#1216 feat(STONEINTG-937): add nightly Gitlab webhooks cleanup
  Makefile
  magefiles/magefile.go
Labels: lgtm, approved, < 1 min

#1232 fix: enable ec
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1235 fix: update quay cleanup regexp
  magefiles/utils.go
  magefiles/utils_test.go
Labels: lgtm, approved, < 1 min

#1233 feat(RELEASE-932): add tags to rh_push_to_external_registry test
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/rh_push_to_external_registry.go
Labels: lgtm, approved, < 1 min

#1239 fix: no extra setup for load tests
  magefiles/magefile.go
Labels: lgtm, approved, < 1 min

#1241 feat: update e2e-tests image in build-tasks-dockerfies repo
  .tekton/update-build-tasks-dockerfiles.yaml
Labels: lgtm, approved, 1-5 min
