Repository konflux-ci/e2e-tests, pull requests merged in 2024-12, with the labels that each got.

#1451 feat(ISV-5130): add Atlas secrets to e2e tests
  integration-tests/scripts/konflux-e2e-runner.sh
  pkg/constants/constants.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/releaseLib.go
Labels: lgtm, ok-to-test, 1-5 min

#1470 fix: update some values in the data of RPA for FBC
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved, < 1 min

#1468 fix: PR pairing
  integration-tests/scripts/konflux-e2e-runner.sh
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, 1-5 min

#1474 chore: store taskRuns in rh_advisiories
  pkg/clients/tekton/pipelineruns.go
  pkg/clients/tekton/taskruns.go
  tests/release/pipelines/rh_advisories.go
Labels: lgtm, approved, < 1 min

#1476 fix: improve Cleanup function
  tests/integration-service/group-snapshots-tests.go
  tests/integration-service/integration.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved, < 1 min

#1475 feat: use secure-push-oci for archiving artifacts
  Dockerfile
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
  integration-tests/scripts/konflux-e2e-runner.sh
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: approved, 1-5 min

#1462 feat: enable ci-helper-app
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: approved, < 1 min

#1479 fix(ISV-5130): use correct atlas secret name
  tests/release/pipelines/rh_advisories.go
Labels: lgtm, ok-to-test, approved, < 1 min

#1480 fix: git repo url should have .git suffix
  pkg/constants/constants.go
Labels: lgtm, approved, < 1 min

#1481 chore: add storeTaskLogs for test cases
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
Labels: lgtm, approved, < 1 min
