Repository konflux-ci/e2e-tests, pull requests merged in 2025-04, with the labels that each got.

#1562 fix: the mrURL can't be found in rh_push_to_redhat_io test
  tests/release/pipelines/rh_push_to_redhat_io.go
Labels: lgtm, approved, < 1 min

#1553 feat(STONEINTG-1114): reflect build PLR failure to intg status in git
  pkg/clients/github/pull_request.go
  pkg/clients/has/components.go
  tests/integration-service/const.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved, 1-5 min

#1559 fix(KONFLUX-7413): tkn-bundle test started failing consistently
  tests/build/tkn-bundle.go
Labels: lgtm, approved, < 1 min

#1561 feat(STONEINTG-1051): e2e for cancelled snapshot and intg plr
  pkg/clients/has/components.go
  pkg/clients/integration/pipelineruns.go
  pkg/clients/integration/snapshots.go
  tests/integration-service/group-snapshots-tests.go
Labels: lgtm, approved, 1-5 min

#1565 fix: variable potential conflict in parallel test
  tests/release/pipelines/fbc_release.go
  tests/release/releaseLib.go
Labels: lgtm, approved, < 1 min

#1564 feat(KONFLUX-7535): New variable for GH action & PaC templating
  .github/workflows/loadtest.yaml
  tests/load-tests/pkg/journey/handle_component.go
Labels: lgtm, approved, < 1 min

#1520 fix: ec pipeline conforma violation in build-template.go
  pkg/utils/tekton/pipelineruns.go
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1452 fix: Changes to users approving scripts
  tests/load-tests/ci-scripts/utility_scripts/show-pipelineruns.py
Labels: lgtm, approved, 1-5 min

#1287 fix(KONFLUX-3854): Cleanup MPC secrets as well if any
  pkg/clients/common/secret.go
  tests/load-tests/pkg/journey/handle_purge.go
Labels: lgtm, approved, < 1 min

#1569 fix: update the revision for the test repo for fbc tests
  magefiles/rulesengine/repos/e2e_repo.go
  magefiles/rulesengine/repos/release_service_catalog.go
  tests/release/pipelines/fbc_release.go
Labels: lgtm, approved, < 1 min

#1573 fix: SA per component test changes
  pkg/framework/framework.go
  pkg/utils/build/git.go
  tests/build/build.go
  tests/build/const.go
  tests/integration-service/const.go
  tests/integration-service/group-snapshots-tests.go
Labels: lgtm, approved, 1-5 min

#1577 chore: increase e2e_timeout to 150m
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, < 1 min
