Repository konflux-ci/e2e-tests, pull requests merged in 2025-06, with the labels that each got.

#1607 chore: no test case will be ran when it's expected
  magefiles/rulesengine/scripts/find_release_pipelines_from_pr.sh
Labels: lgtm, approved, < 1 min

#1608 refactor: label assignment to namespaces
  pkg/clients/common/namespace.go
Labels: lgtm, approved, < 1 min

#1609 feat(KONFLUX-8347): update rh_advisories pattern
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/rh_advisories.go
Labels: lgtm, approved, < 1 min

#1612 fix: GOBIN location
  Dockerfile
Labels: < 1 min

#1613 fix: e2e test runner permissions
  Dockerfile
Labels: approved, < 1 min

#1621 fix: increase imageRepository create timeout
  pkg/clients/has/components.go
Labels: < 1 min

#1627 feat(CLOUDDST-26262): add pyxis params for fbc-release
  tests/release/pipelines/fbc_release.go
Labels: lgtm, ok-to-test, approved, < 1 min
