Repository konflux-ci/e2e-tests, pull requests merged in 2025-01, with the labels that each got.

#1482 fix: make target setup-source-build
  magefiles/magefile.go
  tests/build/build_templates_scenarios.go
Labels: lgtm, < 1 min

#1483 refactor: multiarch_advisories to create new app each time
  tests/release/pipelines/multiarch_advisories.go
Labels: lgtm, approved, 1-5 min

#1484 feat(RELEASE-1296): rh-advisories e2e test should have a cve
  tests/release/pipelines/rh_advisories.go
Labels: lgtm, approved, < 1 min

#1486 fix: docker.io creds to tekton-results postgres SA
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: approved, < 1 min

#1488 feat(): Add json report to the e2e tests for analysis in the future with sealights
  magefiles/magefile.go
Labels: approved, < 1 min

#1487 refactor(RELEASE-1320): update release pipeline pathInRepo values
  tests/build/build.go
  tests/konflux-demo/konflux-demo.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
  tests/release/service/happy_path.go
  tests/release/service/missing_release_plan_and_admission.go
  tests/release/service/release_plan_and_admission_matched.go
Labels: lgtm, approved, < 1 min

#1485 feat(RELEASE-1317): fine tune deployed components for release-pipelines suite
  magefiles/rulesengine/repos/release_service_catalog.go
Labels: lgtm, approved, < 1 min

#1478 chore: remove references to jvm-build-service
  magefiles/magefile.go
  magefiles/utils.go
  pkg/clients/jvmbuildservice/OWNERS
  pkg/clients/jvmbuildservice/artifact_builds.go
  pkg/clients/jvmbuildservice/caches.go
  pkg/clients/jvmbuildservice/controller.go
  pkg/clients/jvmbuildservice/dependency_builds.go
  pkg/clients/jvmbuildservice/jbs_configs.go
  pkg/clients/jvmbuildservice/rebuilt_artifacts.go
  pkg/constants/constants.go
  pkg/framework/framework.go
  tests/build/jvm-build.go
  tests/konflux-demo/README.md
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, ok-to-test, approved, 10-15 min

#1267 fix: adapt konflux-demo for konflux-ci
  tests/konflux-demo/README.md
  tests/konflux-demo/config/scenarios.go
  tests/konflux-demo/const.go
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, 5-10 min

#1492 feat(KFLUXDP-108): Allow to pass via COMPONENT_IMAGE env images with tag and sha
  magefiles/rulesengine/repos/build_service.go
  magefiles/rulesengine/repos/common.go
  magefiles/rulesengine/repos/image_controller.go
  magefiles/rulesengine/repos/integration_service.go
  magefiles/rulesengine/repos/release_service.go
Labels: lgtm, approved, < 1 min

#1495 fix: Match new tekton-pipelines-controller pod name as it is handled by StatefulSet now
  tests/load-tests/cluster_read_config.yaml
Labels: lgtm, approved, < 1 min

#1497 feat: Retry if renaming failed with 'name a repository operation is already in progress' error
  pkg/clients/github/repositories.go
Labels: lgtm, approved, < 1 min

#1493 feat(KFLUXDP-140): Add logic to the tekton task that add a new step to send results to sealights
  default.env
  integration-tests/scripts/konflux-e2e-runner.sh
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: lgtm, approved, 1-5 min

#1498 feat: Support SPDX SBOMs
  pkg/utils/build/sbom.go
  tests/build/build_templates.go
Labels: lgtm, approved, 1-5 min
