Repository konflux-ci/e2e-tests, pull requests merged in 2025-03, with the labels that each got.

#1526 chore: Remove Pat from integration-service's alias list
  OWNERS_ALIASES
Labels: lgtm, approved, < 1 min

#1532 fix: add timeout for bootstrap & e2e
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
  integration-tests/scripts/konflux-e2e-runner.sh
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: approved, < 1 min

#1533 fix: bump go version to v1.22
  .github/workflows/PR.yaml
  Dockerfile
  docs/Installation.md
  go.mod
  go.sum
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
Labels: approved, < 1 min

#1537 fix: exit status of timeout command
  integration-tests/scripts/konflux-e2e-runner.sh
Labels: approved, < 1 min

#1536 fix(KONFLUX-6572): fix retries for WaitForComponentPipelineToBeFinished
  pkg/clients/has/components.go
Labels: lgtm, approved, < 1 min

#1544 feat: Initialize Test Session ID just before running Ginkgo tests
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: < 1 min

#1545 fix: Fix the wrong sealights test session task path
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: approved, < 1 min

#1547 feat: Use Sealights Ginkgo plugin to upload test results to Sealights Dashboard
  Dockerfile
  integration-tests/scripts/konflux-e2e-runner.sh
  integration-tests/tasks/konflux-e2e-tests-task.yaml
  mage
  magefiles/cmd/mage/main.go
Labels: approved, 1-5 min

#1548 feat: Enable debug mode for ginkgo tests to detect Sealights issues
  magefiles/rulesengine/repos/common.go
Labels: lgtm, approved, < 1 min

#1551 feat: Disable by default the Sealights test selections
  integration-tests/scripts/konflux-e2e-runner.sh
  integration-tests/tasks/konflux-e2e-tests-task.yaml
Labels: approved, < 1 min

#1543 refactor(RELEASE-1397): turn release product_ids into lists
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/rh_advisories.go
Labels: lgtm, approved, < 1 min

#1506 feat(RELEASE-1312): change FBC e2e tests back to build a image
  tests/release/const.go
  tests/release/pipelines/fbc_release.go
  tests/release/releaseLib.go
Labels: lgtm, approved, 5-10 min

#1529 feat(RELEASE-1401): add fixed issue in release advisory test
  tests/release/pipelines/rh_advisories.go
Labels: lgtm, approved, < 1 min

#1557 chore: disable tkn-bundle test
  tests/build/tkn-bundle.go
Labels: lgtm, approved, < 1 min

#1555 fix: always update secret
  pkg/clients/common/secret.go
  tests/release/releaseLib.go
Labels: lgtm, approved, < 1 min

#1556 fix: move ReleaseTestHelperFilesChangeOnlyRule
  magefiles/rulesengine/repos/e2e_repo.go
Labels: lgtm, approved, < 1 min

#1550 feat: add option to use oci-ta-bundle
  pkg/constants/constants.go
  pkg/utils/build/custom_bundle.go
  pkg/utils/tekton/bundle.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration.go
  tests/konflux-demo/config/scenarios.go
  tests/konflux-demo/config/types.go
  tests/konflux-demo/konflux-demo.go
  tests/load-tests/pkg/journey/handle_component.go
  tests/release/releaseLib.go
Labels: approved, 5-10 min
