Repository konflux-ci/e2e-tests, pull requests merged in 2025-07, with the labels that each got.

#1595 feat(RELEASE-1263): include new internal pipeline for standalone test
  magefiles/rulesengine/scripts/find_release_pipelines_from_pr.sh
Labels: approved, < 1 min

#1635 fix: graceful cleanup of components
  tests/build/build.go
Labels: lgtm, approved, < 1 min

#1641 fix: use tkn-bundle 0.2 in tkn-bunde test
  tests/build/tkn-bundle.go
Labels: lgtm, approved, < 1 min

#1640 chore(stoneintg-1092a): update IS readme info with new tests
  tests/integration-service/README.md
Labels: lgtm, approved, < 1 min

#1634 chore: log out the err for intg group snapshot tst
  pkg/clients/integration/pipelineruns.go
  tests/build/tkn-bundle.go
  tests/integration-service/group-snapshots-tests.go
Labels: lgtm, approved, < 1 min

#1647 fix: update test cases due attestation_task_bundle remove
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1642 fix: remove toolchain from e2e-tests
  docs/Installation.md
  integration-tests/tasks/konflux-e2e-tests/0.2/konflux-e2e-tests.yaml
  magefiles/installation/install.go
  magefiles/magefile.go
  magefiles/rulesengine/repos/build_service.go
  magefiles/rulesengine/repos/image_controller.go
  magefiles/rulesengine/repos/integration_service.go
  pkg/clients/common/namespace.go
  pkg/clients/common/secret.go
  pkg/clients/gitlab/git.go
  pkg/clients/gitops/controller.go
  pkg/clients/gitops/space.go
  pkg/clients/gitops/space_requests.go
  pkg/clients/kubernetes/client.go
  pkg/clients/tekton/rekor_hosts.go
  pkg/clients/tekton/repository.go
  pkg/clients/tekton/tekton_chains_public_keys.go
  pkg/constants/constants.go
  pkg/framework/framework.go
  pkg/sandbox/sandbox.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/tkn-bundle.go
  tests/enterprise-contract/contract.go
  tests/integration-service/README.md
  tests/integration-service/const.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration-with-env.go
  tests/integration-service/integration.go
  tests/konflux-demo/konflux-demo.go
  tests/load-tests/pkg/journey/handle_purge.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/service/happy_path.go
  tests/release/service/missing_release_plan_and_admission.go
  tests/release/service/release_plan_and_admission_matched.go
  tests/release/service/release_plan_owner_ref.go
  tests/release/service/tenant_pipelines.go
  tests/upgrade/cleanupWorkload.go
  tests/upgrade/create/createUsers.go
  tests/upgrade/createWorkload.go
Labels: approved, 30-60 min
