Repository konflux-ci/e2e-tests, pull requests merged in 2025-09, with the labels that each got.

#1685 fix(STONEINTG-1334): fix groupsnapshots and error handling
  tests/integration-service/group-snapshots-tests.go
Labels: lgtm, approved, < 1 min

#1686 feat: add rerunning push pipeline scenario
  pkg/clients/has/components.go
  tests/build/build.go
  tests/build/build_templates.go
  tests/build/multi-platform.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/integration.go
  tests/integration-service/pipelinerun-resolution.go
  tests/integration-service/status-reporting-to-pullrequest.go
  tests/konflux-demo/konflux-demo.go
  tests/load-tests/pkg/journey/handle_collections.go
  tests/load-tests/pkg/journey/handle_component.go
  tests/load-tests/pkg/journey/handle_pipeline.go
Labels: lgtm, approved, 1-5 min

#1690 fix(STONEINTG-1334): improve the group snapshot suite
  tests/integration-service/group-snapshots-tests.go
Labels: lgtm, approved, < 1 min

#1694 fix: remove retriggering of PLR from upstream test
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, approved, < 1 min

#1697 fix: update konflux-demo test repo git ref
  tests/integration-service/const.go
  tests/konflux-demo/config/scenarios.go
Labels: < 1 min

#1698 fix: multi repo component git revision
  tests/integration-service/const.go
Labels: lgtm, approved, < 1 min

#1706 fix: OverrideMediaType to properly update BUILDAH_FORMAT
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
Labels: lgtm, approved, < 1 min
