Repository konflux-ci/e2e-tests, pull requests merged in 2025-05, with the labels that each got.

#1579 feat(STONEINTG-853): test on-push commit
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, approved, 1-5 min

#1576 fix(tests): change PaC pull request branch prefix
  pkg/constants/constants.go
  tests/konflux-demo/konflux-demo.go
Labels: lgtm, ok-to-test, approved, < 1 min

#1583 fix: Align f.AsKubeAdmin to kubeadminClient in build-template
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1578 fix: test panic for no container log gotten
  pkg/utils/tekton/pipelineruns.go
Labels: lgtm, approved, < 1 min

#1581 feat(RELEASE_1316): enable periodic job for release_service_catalog
  magefiles/magefile.go
  magefiles/rulesengine/repos/release_service_catalog.go
Labels: lgtm, approved, < 1 min

#1588 fix: panic when s.Terminated is nil
  pkg/utils/tekton/pipelineruns.go
Labels: lgtm, approved, < 1 min

#1587 fix(STONEINTG-853): Increasing PLR wait timeout
  tests/integration-service/README.md
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, approved, < 1 min

#1575 feat(STONEINTG-852): add coverage for commit push event
  tests/integration-service/README.md
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved, 1-5 min

#1586 feat(RELEASE-1343): smart selecting test cases for release pipelines suite
  magefiles/magefile.go
  magefiles/rulesengine/repos/release_service_catalog.go
  magefiles/rulesengine/scripts/find_release_pipelines_from_pr.sh
  magefiles/rulesengine/types.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/rh_push_to_external_registry.go
  tests/release/pipelines/rh_push_to_registry_redhat_io.go
Labels: approved, 10-15 min

#1591 Revert "feat: Enable debug mode for ginkgo tests to detect Sealights issues"
  magefiles/rulesengine/repos/common.go
Labels: lgtm, approved, < 1 min

#1592 ci: disable icm-injection-scripts test in build-tasks-dockerfiles
  Makefile
Labels: lgtm, ok-to-test, approved, < 1 min

#1590 fix: label tenant namespaces
  pkg/clients/common/namespace.go
  pkg/constants/constants.go
Labels: lgtm, approved, < 1 min

#1598 chore: deploy konflux failed with tekton components missing
  magefiles/rulesengine/repos/release_service_catalog.go
Labels: lgtm, approved, < 1 min

#1563 feat: add scenario to cover docker mediaType and validations
  Dockerfile
  pkg/utils/build/quay.go
  tests/build/build_templates.go
  tests/build/build_templates_scenarios.go
Labels: lgtm, approved, 1-5 min

#1534 feat(KONFLUX-6960): Introduce hourly jobs
  .github/workflows/loadtest-hourly.yaml
  .github/workflows/loadtest.yaml
  pkg/clients/github/repositories.go
  pkg/clients/gitlab/git.go
  pkg/clients/kubernetes/client.go
  pkg/framework/framework.go
  pkg/sandbox/keycloak.go
  pkg/sandbox/sandbox.go
  pkg/utils/util.go
  tests/load-tests/ci-scripts/collect-results.sh
  tests/load-tests/ci-scripts/stage/cluster_read_config.yaml
  tests/load-tests/ci-scripts/stage/collect-results.sh
  tests/load-tests/ci-scripts/utility_scripts/get-taskruns-durations.py
  tests/load-tests/ci-scripts/utility_scripts/serviceaccount-for-private-cluster.yaml
  tests/load-tests/ci-scripts/utility_scripts/show-pipelineruns.py
  tests/load-tests/loadtest.go
  tests/load-tests/pkg/journey/handle_component.go
  tests/load-tests/pkg/journey/handle_repo_templating.go
  tests/load-tests/pkg/options/options.go
  tests/load-tests/run-max-concurrency.sh
  tests/load-tests/run-stage-max-concurrency.sh
  tests/load-tests/run-stage.sh
  tests/load-tests/run.sh
Labels: lgtm, approved, > 60 min

#1599 fix(STONEINTG): prevent canceling intg pipelineruns
  tests/integration-service/gitlab-integration-reporting.go
Labels: lgtm, approved, < 1 min

#1597 feat: remove appstudio-pipeline SA from release suite
  integration-tests/pipelines/konflux-e2e-tests-pipeline.yaml
  tests/build/build.go
  tests/release/pipelines/fbc_release.go
  tests/release/pipelines/multiarch_advisories.go
  tests/release/pipelines/push_to_external_registry.go
  tests/release/pipelines/release_to_github.go
  tests/release/pipelines/rh_advisories.go
  tests/release/pipelines/rh_push_to_registry_redhat_io.go
  tests/release/pipelines/rhtap_service_push.go
  tests/release/service/happy_path.go
  tests/release/service/missing_release_plan_and_admission.go
  tests/release/service/tenant_pipelines.go
Labels: lgtm, 1-5 min

#1596 fix: cleanup hooks in after all block
  tests/build/build.go
Labels: lgtm, approved, < 1 min

#1602 fix: panic in StoreRelease when Release CR is nil
  pkg/clients/release/releases.go
Labels: lgtm, approved, < 1 min
