Repository konflux-ci/e2e-tests, pull requests merged in 2025-08, with the labels that each got.

#1662 fix: match PipelineTask according for test case: Task are trusted
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, < 1 min

#1663 fix: remove tests for show-sbom Task
  tests/build/build_templates.go
Labels: lgtm, approved, < 1 min

#1673 fix: update conforma task name in release-service happy path
  tests/release/service/happy_path.go
Labels: lgtm, approved, < 1 min

#1676 chore: disable tkn-bundle test temporarily
  tests/build/tkn-bundle.go
Labels: lgtm, approved, < 1 min

#1675 fix: ec-rule used during in build-definitions CI
  pkg/utils/contract/policy.go
  tests/build/build_templates.go
Labels: approved, < 1 min

#1669 chore: cleanup make target and code
  Makefile
  magefiles/magefile.go
Labels: lgtm, approved, 1-5 min

#1677 feat: allow konflux-ci user to access test ns
  pkg/clients/common/namespace.go
  pkg/clients/tekton/rekor_hosts.go
  pkg/clients/tekton/tekton_chains_public_keys.go
  pkg/constants/constants.go
  pkg/framework/framework.go
  tests/enterprise-contract/contract.go
Labels: lgtm, approved, 1-5 min

#1679 fix: configure ginkgo procs based on env var
  go.mod
  magefiles/rulesengine/repos/common.go
Labels: approved, < 1 min

#1680 fix: integration-service e2e case improvement
  pkg/clients/has/components.go
  pkg/clients/integration/pipelineruns.go
  tests/integration-service/group-snapshots-tests.go
  tests/integration-service/pipelinerun-resolution.go
Labels: lgtm, approved, 1-5 min

#1682 fix: enable tekton results test for downstream
  magefiles/rulesengine/repos/infra_deployments.go
  tests/build/build_templates.go
Labels: approved, < 1 min

#1683 fix(STONEINTG-1332-1): integration e2e case improvement
  pkg/clients/integration/pipelineruns.go
  tests/integration-service/const.go
  tests/integration-service/gitlab-integration-reporting.go
  tests/integration-service/group-snapshots-tests.go
  tests/integration-service/integration.go
  tests/integration-service/pipelinerun-resolution.go
  tests/integration-service/status-reporting-to-pullrequest.go
Labels: lgtm, approved, 1-5 min
